from pathlib import Path
import re

base = Path('/Users/asmith/.openclaw/workspace/sportzballz.io')
repls = {
    '2026-04-14.html': [
        "The best way to read this game is by shape: Washington’s yard runs 337 to left-center and 402 to dead center, big enough to reward clubs that keep innings breathing. With warm 78° air and a 14 mph breeze nudging balls toward left, Pittsburgh’s deeper contact chain plays better over nine frames. Pregame availability reports were clean for both sides, so the edge comes from steadier run prevention and fewer empty innings.",
        "In Atlanta, the park gives you 335 down the left line and 400 to center, and on an 82° night with dry air the ball doesn’t need much persuasion. The Braves are healthier through the middle of the order than Miami and bring the more reliable bullpen handoff after the starters exit. That combination makes the favorite less about hype and more about roster continuity.",
        "Kauffman is roomy country—330 at the poles, 410 to center—and it usually rewards the team willing to take singles, extra bases, and clean defense. With 81° warmth but wind pushing in from left, Detroit’s lower-variance style fits the geometry better than a boom-or-bust script. No major late scratches were posted before first pitch, which keeps the Tigers’ depth advantage intact.",
        "Camden’s redesign still matters: 333 to left, a deep left-center pocket, and 410 to center make one-dimensional power lineups work harder. In 88° heat with a light wind to center, Arizona’s speed-plus-gap offense has room to pressure defenders all night. Injury notes at publish time showed no fresh absences among key Diamondbacks bats, so the plus price still looks playable.",
        "Busch plays larger than people remember—336 to left and 400 to center—but on an 88° evening with a 16 mph push toward left, doubles can arrive in bunches. St. Louis has the healthier lineup balance right now and more ways to score without waiting on one swing. With no late injury downgrade in the posted card, the underdog tag offers value.",
        "Rate Field is straightforward math: 330 down each line, 400 to center, and tonight a heavy 76°/humid setup with wind blowing in from left. That weather trims cheap carry and rewards the club that wins counts early, which points toward Tampa Bay’s strike-throwing profile. No surprise lineup scratches surfaced pregame, so the Rays’ cleaner pitching path remains the better side.",
        "Petco after sunset is usually a patience exam, with deep alleys and marine air swallowing marginal fly balls. At 66° with wind drifting in from right, Seattle’s efficient starter-to-bullpen sequence is the right fit for this lower-scoring environment. San Diego entered with one lineup spot still unsettled at publish time, and that uncertainty tilts the game-state edge to the Mariners.",
        "The Bronx is loud geometry—short porches, 408 to center, and almost no forgiveness for missed locations—especially at 84° with breeze to center. New York’s lineup is healthier through the power lanes and can stack traffic even when the homers pause for an inning. With both cards posted and no late scratch headline, the Yankees own the sturdier run-creation floor.",
        "Dodger Stadium at 62° plays fairer than flashy, and that usually rewards depth over drama. The dimensions (330-400-330 with broad alleys) still demand complete at-bats, and Los Angeles has more of them 1-through-9 than New York tonight. No major injury surprise hit the Dodgers card before lock, so the safer full-game profile stays on the home side.",
        "Roof games strip excuses, and in Milwaukee’s 328-400-328 room the better sequencing usually wins. The Brewers carry healthier table-setters right now, which matters against a veteran opponent that prefers clean, static innings. With no late pregame scratch among Milwaukee’s regulars, the side has more paths to manufacture runs.",
        "Target Field can be honest baseball—339 down left, 404 to center—and tonight’s cool 63° air with light wind to right keeps it that way. Minnesota’s defensive reliability and available core bats fit a game likely decided by one or two medium innings, not fireworks. Boston arrives competitive, but with no fresh injury boost on their side the plus price on the Twins is still attractive.",
        "In Cincinnati, the dimensions are blunt (328 down left, 404 center, 325 right), and 85° heat with wind to left can turn routine mistakes into crooked numbers. San Francisco’s advantage is not spectacle; it is steadier early count work from the starter and fewer free baserunners late. Pregame reports showed no new lineup losses, so the Giants keep the cleaner nine-inning blueprint.",
        "Sacramento’s temporary big-league setup plays roughly 330 to the lines and about 403 to center, enough room for gap baseball when the evening cools. With temperatures in the mid-60s and only a mild breeze out to center, Texas benefits from the deeper offensive floor and healthier middle-order availability. No late injury surprise shifted that balance before publish.",
        "Citizens Bank remains compact at 329 and 330 down the lines, and on an 86° night with wind pushing to right, every elevated mistake gets expensive. Philadelphia enters with more everyday bats available and the cleaner leverage-inning bridge behind the starter. With both lineups posted free of major scratch news, the Phillies deserve favorite status."
    ],
    '2026-04-14-plus-money.html': [
        "As a dog ticket, Arizona has the right map: run into Camden’s deep left-center gap (333-410 geometry), pressure the extra base, and force Baltimore to execute throws all night. In 88° heat with breeze toward center, balls stay lively in the alleys where this lineup does its best work. With no late injury red flag in the posted order, the price is richer than the separation.",
        "St. Louis doesn’t need miracles here—just Busch weather working with them: 88° warmth, firm wind out to left, and a park that stretches defenses once line drives start skipping. The Cardinals’ lineup card came in without fresh absence news, while Cleveland still profiles more volatile inning to inning. At plus money, that steadier health-and-contact profile is enough.",
        "Target Field’s 339-404 frame usually rewards complete baseball, and tonight’s cooler air keeps run creation tied to quality at-bats, not cheap carry. Minnesota shows fewer pregame availability concerns among core contributors, which matters in the likely one-run pockets of this matchup. In a game shaped by execution, the underdog price on the Twins is justified."
    ],
    '2026-04-14-run-totals.html': [
        "OVER 9.5 fits because Nationals Park is built for sustained offense in warm weather: 337 down left, 402 to center, and long gaps that turn sharp contact into extra bases. At 78° with wind pushing toward left, innings can stretch through doubles and relays even without a homer barrage. Both lineups entered without major late scratch news, keeping the run environment elevated.",
        "Great American is small by design—328 and 325 down the lines—and 85° heat with a 15 mph push toward left is classic over weather. Even solid pitch execution can still leak damage in this park because one misplaced fastball changes the inning. Neither side carried a late headline injury to the middle order, so the over remains live throughout.",
        "OVER 8.5 is defensible at Busch when the thermometer is near 89° and wind is running out toward left. The field is spacious (336-400-335), but that weather pulls warning-track contact into playable run creation. With both offenses largely intact on pregame reports, this total can clear through steady pressure rather than one blowup frame.",
        "Yankee Stadium plus warmth is always an over conversation: short corners, dangerous right-field porch, and 84° air with breeze to center. The number only needs recurring traffic because this geometry punishes even medium-loud contact. With no major lineup injury shock before first pitch, OVER 9.0 has multiple routes home.",
        "At Truist (335-400-325), 82° dry air and light wind out to left support carry, but the stronger case is lineup quality turning innings over. Atlanta can force long counts early, and Miami can still add late scoring against middle relief. No major pregame scratches were posted, so OVER 8.83 holds up on depth as much as weather.",
        "Camden’s deeper left field suppresses some pull power, yet 88° heat and breeze to center open the alleys for doubles and first-to-third baseball. That combination often lifts totals without requiring four homers. With core bats available for both clubs at publish time, OVER 8.75 remains a fair target.",
        "Citizens Bank is compact (329-401-330), and tonight’s 86° conditions with wind to right make 8.25 modest if either starter loses command once. The park rewards lifted contact and aggressive baserunning in equal measure. Both lineups were posted without major injury downgrades, supporting an over script built on repeated pressure.",
        "UNDER 8.33 makes sense at Rate Field when the weather is humid and the wind is blowing in from left around 17 mph. The dimensions are ordinary, but this airflow steals just enough carry to strand medium-quality contact. With no fresh pregame activation of injured sluggers, the under gets a cleaner run-prevention path.",
        "Petco’s nighttime profile leans under almost by habit: dense marine air, deep alleys, and wind pushing in from right near 10 mph. Even with talent present, seven runs is a high bar when hard contact dies before the wall. Pregame reports showed no surprise returns from injury that would materially change the run outlook.",
        "Dodger Stadium’s 330-400-330 layout is neutral on paper, but with complete lineups and strong top-six bats on both sides, OVER 8.0 is reachable through sequencing. At 62° you’re not banking on cheap carry; you’re banking on repeated quality plate appearances. No significant late scratch news reduced that offensive depth.",
        "Target Field at 63° can play controlled, yet OVER 7.88 is still viable because both offenses have enough healthy contact plus gap power to produce in clusters. The large center field (404) creates room for doubles and defensive stress. With neither team announcing a major pregame injury setback, eight runs is within normal range.",
        "Comerica’s big dimensions (345 and 330 lines, 412 to center) and wind blowing in from left support UNDER 7.88. This park asks for strings of quality contact, and that is hard to sustain when the air knocks down carry. With no notable pregame return of missing middle-order power, the under case stays intact.",
        "For Rangers-Athletics, OVER 9.5 is about game flow more than park inflation: mild weather, neutral-to-fair dimensions, and two lineups capable of extending innings with speed and doubles. In this setup, run production can arrive in twos and threes across several frames. Pregame availability reports showed no major offensive scratches, preserving that over pathway.",
        "UNDER 7.0 in a roof environment is a command bet: stable air, no weather lift, and a park that plays close to neutral when pitchers get ahead. Milwaukee and Toronto can both quiet down for stretches against strike-throwers, making every baserunner matter. With no late injury news forcing weaker arms into key spots, the under remains the sharper side."
    ]
}

for fn, arr in repls.items():
    p = base / fn
    t = p.read_text()
    ms = list(re.finditer(r'<p class="lede">.*?</p>', t, flags=re.S))
    assert len(ms) == len(arr), (fn, len(ms), len(arr))
    out = []
    last = 0
    for m, n in zip(ms, arr):
        out.append(t[last:m.start()])
        out.append(f'<p class="lede">{n}</p>')
        last = m.end()
    out.append(t[last:])
    p.write_text(''.join(out))
    print('updated', fn)
