from pathlib import Path
import re

base=Path('/Users/asmith/.openclaw/workspace/sportzballz.io')

repls={
'2026-04-14.html':[
"Pittsburgh gets the nod because this game sets up for cleaner innings on both sides of the ball: Keller’s sinker profile fits PNC Park’s deep left-center alley (325 down the line, 410 to center), and the Pirates’ contact quality has traveled better inning to inning than Washington’s. With first pitch in 78-degree air and a 13.7 mph breeze pushing toward left, run scoring should come in bursts, so defensive sequencing and bullpen strike-throwing matter even more. Both clubs posted full announced lineups and the injury sheet lists no fresh star absences, which keeps the edge on the steadier staff-and-glove side.",
"Atlanta is the side because the matchup is built for their middle-order damage at Truist Park (335 to left, 400 to center, 325 to right) against a Miami staff that still leaks extra-base contact when forced into the middle innings. The weather is dry and lively—81.8°F with a light wind toward left—so hard contact should carry, and that usually rewards the deeper offense over nine frames. With both lineups announced and no late-impact injury scratch on either core, the better baseline run-creation profile stays with the Braves.",
"Detroit’s case is about run prevention under Comerica geometry (big 420-foot center field, spacious left-center) plus a starter matchup that should keep loud contact from becoming crooked numbers. The 10.5 mph wind blowing in from left at 81°F trims the cheap home-run path and emphasizes doubles, range, and bullpen command. Even with lineups still pending, the injury report does not show a new everyday bat unexpectedly out, so the safer path belongs to the club built for long at-bats and gap defense.",
"Arizona as a plus side is worth the bite because Camden’s long center field (410) still plays smaller in heavy warmth, and 87.8°F with wind out to center boosts carry for line-drive hitters on both rosters. In that environment, the cleaner route is the club that strings singles-plus-advancement instead of waiting for one swing, and that has been Arizona’s recent shape. Both lineups are posted, and the injury board is stable enough that the underdog price feels richer than the game-state difference.",
"St. Louis is playable as a slight dog because Busch Stadium’s broad power alleys (375 each gap, 400 to center) can flatten one-dimensional power and reward clubs that manufacture the extra 90 feet. At 88.5°F with a 16 mph wind moving toward left, run expectancy rises, but sequencing and bullpen walk control become the separator. Both teams have announced lineups and no fresh headline scratch, so the value remains on the side with the more reliable inning-to-inning structure.",
"Tampa Bay earns the call in a game where weather fights offense: 17 mph wind in from left at Rate Field (330/400/335) should knock down several fly balls that are homers on calmer nights. That steers the matchup toward strike throwing, contact management, and bullpen leverage, areas where the Rays are still more bankable right now. Lineups are not final yet, but the injury sheet shows no new late removal of centerpiece hitters, so the favorite still owns the cleaner map.",
"Seattle has the better pathway at Petco because the ballpark’s marine layer and deep right-center geometry already suppress damage, and tonight’s 10.2 mph wind in from right reinforces that run environment. In lower-scoring scripts, first-pitch strike rate and late-inning reliever command swing outcomes, and the Mariners profile better there than San Diego’s current shape. Seattle’s lineup is in while the Padres were still pending at publish, and no major injury shock altered the pregame read.",
"The Yankees are priced high for a reason: even with Yankee Stadium’s famous short porch in right (314 feet), this matchup is less about cheap fly balls and more about sustained traffic against an Angels staff that has struggled to escape the third-time-through pressure. At 84.1°F with wind nudging to center, the run environment is active, and New York’s lineup depth is built for that kind of game. Both cards are posted and the injury report shows key bats available, keeping the edge with the heavier offense.",
"Los Angeles is the side despite the ugly listed number because Dodger Stadium still rewards complete games from complete rosters—330 down the lines, roomy gaps, and enough cool night air to expose thin bench depth late. With Yamamoto opposite a less proven arm and both lineups confirmed, the quality gap shows up most after the fifth inning when command and defensive efficiency decide extra baserunners. Weather is mild (62.5°F, light breeze to right), so the game should play cleanly and favor the deeper club.",
"Milwaukee gets the nod in the roof-controlled setting of American Family Field, where the consistent backdrop and moderate dimensions (roughly 344 to left, 400 to center, 345 to right) reduce weather noise and put the focus on execution. That favors the team whose offense creates pressure with pace and whose staff limits free passes once the order turns over. With no late injury surprise removing a core bat and lineups expected near first pitch, the Brewers remain the sturdier side at this price.",
"Minnesota is a live plus-money side because Target Field’s deep center (411) and broad alleys reward doubles power and outfield range more than pure pull-homer hunting. In 62-degree air with only a mild breeze to right, this projects as a sequencing game, and the Twins’ current contact quality gives them enough paths to win even against name-brand pitching. Both lineups are announced and no critical injury downgrade hit pregame, so the underdog ticket has real structure.",
"San Francisco is the side in Cincinnati because Great American’s compact lines (328 left, 325 right) plus 85-degree heat and a 15 mph wind to left create scoring volatility that punishes shaky command. In those conditions, the preferred team is the one more likely to get length from its starter and force fewer high-leverage bullpen outs. Lineups were still pending, but there is no fresh injury bombshell on either club, leaving the edge with the more stable prevention profile.",
"Texas is still the better side in Sacramento’s Sutter Health Park, where modest dimensions and evening air can turn routine fly balls into stressful innings if pitchers miss arm-side. The weather is neutral-to-friendly for hitters (mid-60s, breeze out to center), so defensive conversion and bullpen strike percentage become critical late. Both lineups are in and no key injury news flipped the card, which supports backing the deeper roster despite the market oddity.",
"Philadelphia is the call because Citizens Bank Park (329 to left, 330 to right, power alleys that play quick in heat) is built for pressure offenses, and tonight’s 85.9°F with wind out to right enhances that profile. When the environment tilts toward offense, the club that controls counts and protects the middle innings usually cashes, and that has been the Phillies’ cleaner path. Both lineups are posted, injury reporting is stable, and the matchup shape justifies laying the number."
],
'2026-04-14-plus-money.html':[
"Arizona at plus money is attractive because Camden’s summer-style heat in mid-April (87.8°F) and wind to center can flatten the favorite/underdog gap fast. The park’s long center field (410) still rewards line-drive continuity and smart baserunning, and that is where Arizona has looked cleaner recently. With both lineups announced and no late injury subtraction to either core, the underdog number gives more value than the actual separation between these teams tonight.",
"St. Louis as an underdog fits a classic Busch script: big gaps, extra first-to-third opportunities, and a game likely decided by who throws more competitive strikes in innings six through eight. The weather (88.5°F, 16 mph to left) boosts offense, but Busch’s 400-foot center and roomy alleys still reward disciplined run manufacturing. Both clubs are near full strength on the injury sheet and have lineups posted, so the plus tag is worth taking on the more orderly game plan.",
"Minnesota at a plus number works because Target Field’s dimensions (especially 411 to center) reduce easy power and turn this into a depth-and-defense contest. In cool low-60s air with only a light breeze, run creation should come from sequencing, not cheap carry, which narrows the practical gap with Boston. With both lineups confirmed and no major late injury swing, the underdog side has enough real paths to justify the price."
],
'2026-04-14-run-totals.html':[
"OVER 9.5 is justified at PNC because warm air (78.2°F) and a firm breeze out to left should add carry in a park that already gives left-field line drives room to split defenders before the wall. With both lineups available and no major pregame scratch removing middle-order bats, each club has a plausible four-plus run route. The dimensions still protect center, but the weather pushes this game toward extra-base volume and late bullpen stress.",
"OVER 8.8 in Cincinnati tracks with the full setup: Great American’s tight foul-pole distances, 85-degree heat, and 15 mph wind to left create one of the stronger run environments on the slate. Even routine contact can become immediate pressure there, and both offenses profile to force high-leverage bullpen outs. Unless command is unusually sharp early, this park-weather combination usually drifts toward an over pace.",
"OVER 8.25 at Busch is a weather-driven but still defensible number: 88.5°F and a 16 mph push to left raise carry, while both clubs have enough lineup continuity to string innings together. Busch’s deep center field can suppress the pure homer binge, yet it also creates gap traffic and RBI chances when outfielders play honest depth. That mix often lands in the 5-4 or 6-4 band, which clears this total.",
"OVER 9.0 in the Bronx lines up with the conditions and the park map. Yankee Stadium’s short right-field porch plus 84-degree warmth and a light breeze out to center expand home-run probability for both handedness profiles, not just lefty pull power. With both lineups posted and no key late scratches, the game has enough on-base volume to threaten this number by the middle innings.",
"OVER 8.88 in Atlanta is more about sustained offense than one inning chaos. Truist Park plays fair but active in warm dry weather (81.8°F), and wind to left gives right-handed authority bats a small but meaningful carry bump. If starters exit before turning over cleanly a third time, both bullpens are likely to face inherited traffic, which keeps the over in range.",
"OVER 8.8 at Camden is a strong environmental call: 87.8°F with wind out to center turns hard contact into extra carry, and this ballpark can play smaller in those conditions despite the deeper left-field redesign and 410-foot center lane. Both teams bring enough top-half lineup punch to create early scoring, and neither injury report removes the main run producers. This total has multiple paths to nine or more.",
"OVER 8.3 in Philadelphia is supported by park physics and weather. Citizens Bank’s compact dimensions, especially to right, pair with 85.9°F and wind in that same direction, creating favorable flight for lifted contact. With both offenses close to full pregame availability, a modest number like 8.3 leaves little margin for ordinary bullpen leakage.",
"UNDER 8.12 for Rays-White Sox is a weather-and-shape play: 17 mph wind in from left at Rate Field takes distance off elevated contact, and that park already asks hitters to drive the gaps to score in bunches. If both starters hold command through two turns, this can settle into a low-traffic game with scattered solo threats instead of crooked innings. The under benefits from the wind profile more than the market is pricing.",
"UNDER 7.0 at Petco is consistent with venue identity and tonight’s air. Petco’s marine layer, deeper alleys, and a 10.2 mph wind in from right all suppress carry, so run creation should require stringing multiple quality plate appearances. That usually caps upside unless one starter loses the zone completely, making a 3-2/4-2 style finish the most common lane.",
"OVER 8.0 in Los Angeles is a measured over, not a fireworks call. Dodger Stadium’s dimensions are neutral, but both lineups are intact and capable of forcing starter exits by the fifth if pitch counts climb. With mild weather and no rain risk to interrupt rhythm, this projects as a steady accumulation game where nine runs is reachable without a single monster inning.",
"OVER 7.9 in Minneapolis makes sense because the number is modest for two offenses that can convert doubles lanes in a park with deep center and playable gaps. Cooler air holds some fly balls, but it also keeps pitchers in the zone, which can raise contact volume when command isn’t precise at the edges. With both lineups announced and no major injury subtraction, eight runs is a fair expectation band.",
"UNDER 7.9 at Comerica fits the geometry: huge center field and deep alleys turn potential homers into track-ball outs, and tonight’s wind in from left further trims carry. Even at 81°F, this is still a park where scoring often requires three events in sequence. Unless defensive execution breaks down, the under has the cleaner path.",
"OVER 9.5 for Rangers-Athletics is a park-and-depth over. Sutter Health Park can play lively in the gaps, and the mild breeze to center gives extra travel to elevated contact as bullpens get exposed late. With both lineups posted and no major last-minute injury subtraction, this total leans toward cumulative scoring rather than a dead middle.",
"UNDER 7.0 in Milwaukee is a controlled-environment read: with the roof setup limiting weather volatility, run scoring depends mostly on starting-pitcher efficiency and chase management. American Family Field is not extreme in either direction, so a low total can still hold if both clubs avoid free passes and keep traffic to singles. The injury report does not introduce new middle-order absences, but the structure still points to a tight, lower-event game."
]
}

for fn, new_ledes in repls.items():
    p=base/fn
    txt=p.read_text()
    pattern=r'<p class="lede">.*?</p>'
    old=re.findall(pattern, txt, flags=re.S)
    if len(old)!=len(new_ledes):
        raise SystemExit(f"count mismatch {fn}: {len(old)} vs {len(new_ledes)}")
    def repl_factory(vals):
        it=iter(vals)
        def _r(m):
            s=next(it)
            return f'<p class="lede">{s}</p>'
        return _r
    txt2=re.sub(pattern, repl_factory(new_ledes), txt, flags=re.S)
    p.write_text(txt2)
    print('updated', fn)
