from pathlib import Path
import re

base=Path('/Users/asmith/.openclaw/workspace/sportzballz.io')
repls={
'2026-04-14.html':[
("Pittsburgh is the steadier side in a game shaped by PNC’s roomy alleys (325 to left, 410 to center, 320 to right) and a 13.7 mph crosswind that can turn hard contact into long outs. Mitch Keller’s sinker profile fits that geometry, while Washington still leans on streaky run creation. With both lineups posted and no late core absences flagged, the favorite has the cleaner nine-inning path.",
"PNC can make a loud swing feel like a rumor by the warning track, and tonight’s broad outfield lanes plus cross-breeze keep rewarding the club that strings quality innings together. Keller’s heavy fastball profile is built for this 325-410-320 canvas, while Washington still runs colder stretches once traffic appears. With both lineups posted and no headline absences, Pittsburgh owns the steadier route through the middle frames."),
("At Truist (335-400-325), this plays like an Atlanta control game: enough carry in warm 81.7° air, but not enough wind to erase the pitching edge. Reynaldo López gets a Marlins lineup that can go quiet for stretches, and Atlanta’s middle-order health looks stable entering first pitch. Price is chalk, but the matchup logic is cleaner than the ticket cost.",
"Truist in warm, dry air usually rewards authority, and Atlanta brings more of it without needing wind assistance to cash. López should work into quieter pockets of this Miami order, then hand a lead to the deeper relief bridge. With the Braves’ run-producing core available, the favorite price is less glamour than simple roster advantage."),
("Comerica’s long corridors (345 down the left-field line, 412 to dead center, 330 to right) reward teams that manufacture extra bases and prevent the crooked inning. Detroit’s profile fits that better tonight, even in 81.8° weather with a crosswind that won’t consistently aid pull power. If lineups arrive without surprises, the Tigers’ run-prevention shape keeps them in front of this number.",
"Comerica asks for patience: 345 to left, 412 to center, and very few cheap souvenirs when clubs lose discipline. Detroit is built for that kind of evening—defense first, selective damage, and fewer self-inflicted innings. Even in warm weather, this park still taxes impatient offenses, so the Tigers’ cleaner prevention profile carries weight."),
("Camden Yards still asks right-handed power to work through deep left-center space, and that matters in a game expected to be decided by sequencing more than one swing. Arizona’s offense is healthier at the top and better built for doubles-and-pressure baseball, while 88.2° heat and a breeze to center add just enough volatility for a plus-money live dog. Kelly doesn’t need dominance here—just six composed innings.",
"Camden no longer gives away left-field damage, so this matchup leans toward clubs that run the bases hard and keep passing the baton. Arizona checks that box, and the hot 88-degree air with a light push to center adds chaos that favors active lineups over waiting games. With Kelly’s job reduced to six composed innings and the top of the order intact, the underdog price remains attractive."),
("Busch Stadium (336-400-335) with 15 mph wind pushing to center is a different place than its low-scoring reputation, especially in near-90° air. St. Louis has more ways to score in that environment, and its key bats are all available on the pregame board. In a near-pick’em game, the side with better damage potential in these conditions gets the nod.",
"Busch can look spacious on paper, then play lively when warm air and a 15 mph push get involved. That is tonight’s setup, and St. Louis arrives with enough healthy right-left balance to exploit it over multiple innings. In a coin-flip market, the club with more paths to extra-base damage deserves the lean."),
("Rate Field’s broad center field (400 feet) and a damp crosswind setup favor pitchers who can miss barrels, and that points toward Tampa Bay behind McClanahan. Chicago’s young arms can flash stuff but still run high-stress counts, which is dangerous against a patient Rays order. Unless a late lineup scratch changes the top six hitters, this is Tampa’s matchup to control.",
"Rate Field’s deep center and heavy air put a premium on clean strike one, and McClanahan usually wins that argument early. Chicago can miss bats, but long counts against Tampa often become bullpen stress by the fifth. If the lineup cards stay close to expectation, this is the kind of game the Rays typically control by accumulation."),
("Petco’s dimensions (334-396-322) and marine night air already compress offense; add a 9.7 mph breeze blowing in from center and every run gets expensive. That setting favors Seattle’s style with Bryan Woo attacking the zone and forcing contact quality down. San Diego’s lineup uncertainty at publish time only strengthens the case for the steadier side.",
"Petco after dark is baseball in lowercase: big outfield alleys, heavier air, and a breeze that asks hitters to earn every deep fly. Woo’s tempo and strike efficiency fit that script, forcing San Diego to build innings the hard way. With the Padres still sorting their final lineup spots, Seattle carries the cleaner nine-inning plan."),
("Yankee Stadium can flip a game in one inning, but tonight’s edge is broader than the short porches (318 left, 314 right, 399 center). In 84.7° warmth with wind drifting out, New York still owns the superior run-creation floor, and its core bats are active. If this turns into a bullpen game by the sixth, the Yankees are better equipped to win the leverage outs.",
"Yes, the porches are short, but this case isn’t a one-swing fairy tale; it is about which roster keeps pressure on from inning one through the bullpens. In warm air with a helping breeze, New York’s active middle order should produce steady traffic, not just occasional fireworks. Once leverage innings arrive, the Yankees still hold the deeper late-game options."),
("Dodger Stadium’s 330-395-330 frame and mild 62.6° evening usually reward complete rosters, not hopeful scripts. Los Angeles brings the deeper offense and the cleaner starter matchup, and the Mets’ path depends on near-perfect traffic management. With both lineups confirmed, the home side remains the higher-probability grind over nine innings.",
"Dodger Stadium at 62 degrees tends to reward depth more than drama, and depth is where Los Angeles separates. Yamamoto gives the home side the cleaner opening posture, then a deeper lineup can keep nudging pressure against a thinner run-prevention path. With both cards posted, the Dodgers still own the sturdier full-game shape."),
("Inside American Family Field (344-400-345), weather noise drops and execution decides it. Milwaukee’s young power-speed mix plays well in that neutralized environment, and its active lineup board suggests no missing centerpiece bats. Against a veteran starter, the Brewers still project to create more pressure inning to inning.",
"Under a roof, excuses disappear: same light, same air, same geometry, and the better execution usually wins. Milwaukee’s active lineup brings more legs and more second-to-home pressure, which matters against a veteran who thrives when innings stay static. The Brewers are the side more likely to force motion on every base."),
("Target Field (339-403-328) in 64.5° air with only a light breeze to center should play fair, not explosive. That suits Minnesota, which can win with run prevention and timely extra-base contact rather than a home-run race. With Buxton and the core group available, the plus price is playable on structure alone.",
"Target Field tonight is neutral enough that fundamentals can decide it: first-pitch strikes, clean defense, and timely doubles. Minnesota’s healthy core, including Buxton, is built for exactly that kind of low-drama game script. At plus money, that steadier blueprint is worth buying."),
("Great American Ball Park is tight down the lines (328 and 325) and can get loud fast in 80° weather, but this handicap leans on starting-pitch quality more than park fear. San Francisco has the cleaner mound profile for the first two trips through the order, and that matters in a venue where early jams spiral quickly. If neither club loses a late bat, the Giants have the calmer path.",
"Great American turns mistakes into souvenirs in a hurry, so the opening two trips through the order matter more than usual. San Francisco enters with the cleaner starter profile to survive that first wave, then hand off without panic. In a park where innings can unravel fast, the calmer mound path is the right tiebreaker."),
("Sutter Health Park’s Sacramento layout (330-403-325) plays fairer at night, and 64.8° air with modest breeze out to center should keep the game from becoming a cheap-homer derby. Texas owns the stronger top-of-order on-paper and arrives with key regulars listed active. In a near-even market, that roster stability is enough to side Rangers.",
"Sacramento nights usually bring this park back toward honest baseball—long enough gaps, cooler air, and fewer cheap carry balls. Texas has the more reliable top-third lineup and enters with cornerstone bats available, which matters in a near-pick’em setup. Small edges count most in neutral conditions, and the Rangers hold more of them."),
("Citizens Bank Park (329-401-330) with 86.3° heat is built for carry, especially when mistakes leak to the pull gaps. Philadelphia’s lineup is healthy where it matters and better positioned to cash those mistakes than Chicago tonight. With Nola set to work at home, the Phillies hold the sharper run expectancy profile.",
"Citizens Bank in mid-80s heat is a place where one missed location can change the inning’s obituary. Philadelphia brings the healthier impact bats for that environment, and Nola gives them the cleaner foundation before the game reaches the leverage relievers. In this weather, the Phillies’ run-creation floor is the safer side."),
],
'2026-04-14-plus-money.html':[
("Underdogs need a real map, and Arizona has one tonight: gap pressure in Camden’s deeper left-center, plus enough speed to turn singles into immediate stress. The 88.2° heat with breeze to center can flatten command late, which helps the side that strings contact instead of waiting for one blast. With the principal bats available, this dog is priced wider than the matchup warrants.",
"A live dog needs a believable script, and Arizona owns one: line-drive pressure into Camden’s big left-center pocket, then speed that turns routine hits into decisions. In hot air with a breeze toward center, command can drift late, which favors the lineup that keeps passing runners along. With key bats available, this price is richer than the matchup gap."),
("This is the kind of plus number worth taking—small edge, big weather assist. Busch is playing warm and wind-aided to center, which widens scoring paths for a Cardinals lineup that has its main run producers active. In a game expected to hinge on middle innings, that environment gives St. Louis a little more upside than the market implies.",
"This is the underdog ticket that ages well: modest talent gap, meaningful weather nudge, and a lineup that arrives mostly intact. Warm air and a firm push at Busch expand run paths for St. Louis, especially once bullpens start mixing and matching. In that middle-innings grind, the plus tag on the Cardinals still feels inflated."),
("Target Field won’t gift many cheap runs tonight, so execution and bullpen shape matter more than brand name. Minnesota’s active core and cleaner defensive profile make them live at this price, especially in a game likely decided by one or two sequencing moments. If this stays in the eight-run neighborhood, the dog remains very much alive.",
"Target Field is offering no carnival effects tonight, which is excellent news for a disciplined underdog. Minnesota brings a healthy core and the cleaner defensive baseline, exactly the profile that steals one-run games from better-known brands. If this stays in the typical 4-3, 5-4 neighborhood, the price on the Twins is generous."),
],
'2026-04-14-run-totals.html':[
("With 79° warmth and a 13.7 mph crosswind at PNC, this total leans over because contact should stay in play all night, forcing extra defensive chances. The park’s deep middle (410 feet) cuts some homers but also creates long run-scoring innings through doubles and first-to-third pressure. Both lineup cards are intact enough to support traffic rather than waiting on solo shots.",
"PNC’s deep middle does mute easy homers, but in warm air and cross-breeze conditions it also manufactures long innings through doubles, cutoffs, and extra ninety-foot decisions. That profile often lifts totals without needing a homer parade. With both lineups largely intact, the over path is sustained traffic rather than isolated blasts."),
("Great American’s compact lines (328 to left, 325 to right) are tailor-made for overs once temperatures rise into the 80s. Add the crosswind and this park turns medium contact into stressful innings quickly. With both offenses built to attack mistakes early in counts, the total still leans upward despite the already-high number.",
"In Cincinnati, warm weather plus short lines usually means an over is live before the anthem ends. This yard punishes even modest mistakes, and tonight’s breeze only adds to the stress on any elevated fastball. Even at a high opener, the run environment still points upward."),
("In Busch, 15 mph wind out to center and near-90° heat are enough to upgrade ordinary contact into warning-track trouble and occasional carry-outs. With both offenses showing full-strength top halves, 8.5 is a fair over number in this specific weather window. The forecasted run environment is more offensive than the stadium’s reputation.",
"Busch has an old pitcher’s-park reputation, but not on a hot night with a real push to center. Those conditions turn routine fly balls into live scoring events and deepen bullpen exposure by the sixth. With both top halves healthy, 8.5 still sits a touch low for this weather band."),
("Yankee Stadium’s short porches and warm 84.7° conditions usually put pressure on any total in the high eights, especially with wind nudging balls toward center. Even routine fly contact can become extra-base offense in this setup. With both clubs carrying active middle-order bats, this number leans over on park math and weather alone.",
"At Yankee Stadium, warm air and short corners force every total to answer hard questions, and tonight adds a modest tailwind to center. You do not need perfect barrels here—just enough loft and traffic. With both middle orders active, the over has multiple clean paths."),
("Truist’s 335-400-325 dimensions plus dry, warm air make 8.5 a reachable number if either starter loses the zone once. Atlanta’s run creators are available, and Miami has enough athletic contact to contribute its share against the back half of the game. This projects as an over built on sustained baserunners, not miracle homers.",
"Truist in warm, dry conditions can run fast once one starter labors through a 25-pitch inning. Atlanta’s healthy run creators set the pace, and Miami has enough speed-contact pieces to add scoring late against middle relief. This over is built on traffic and sequencing, not lottery-ticket homers."),
("Citizens Bank is a carry park in hot air, and 86.3° with breeze across to right keeps the ball lively all evening. The dimensions (329-401-330) reward pull-side authority from both lineups’ core hitters, all of whom are available. Ten runs is not a stretch in this weather-and-park combination.",
"Citizens Bank plus heat is one of the friendlier over equations on the board. The 329-401-330 geometry rewards pull authority, and tonight’s warmth keeps even medium contact dangerous to the gaps. With impact bats available on both sides, nine and a half is still chaseable."),
("Comerica is still one of the better under parks because of its deep power alleys and 412-foot center, and that geometry matters more than the warm temperature. Even with decent hitting conditions, many fly balls die into outs here, especially when both starters can work ahead. The under case is about limiting damage swings and forcing three-hit rallies.",
"Comerica remains a difficult place to clear with authority—big alleys, 412 to center, and lots of loud outs. Even in warm weather, this under is more about geometry than temperature. If both starters stay ahead in counts, rallies should require too many consecutive quality swings."),
("Camden’s remodeled left-field depth still steals extra-base damage from right-handed pull power, and that supports an under at this unusual number. Even in 88° weather, long fly balls can die in that part of the park before they become crooked innings. If starters avoid free passes, this total trends to a tighter scoring game than the heat suggests.",
"Camden’s deeper left field still matters, especially against right-handed lift that used to leave in a hurry. Hot weather helps offense, but this number is high enough that one suppressed power lane can swing the result. If free passes stay modest, the under has room."),
("Rate Field’s larger center gap and a humid, crosswind night profile point to suppressed slug unless hitters square mistakes perfectly. Tampa and Chicago can both create strikeout-heavy stretches, which is exactly what under tickets need at this number. A couple of solo homers can happen and still leave this under live deep into the eighth.",
"Rate Field’s deep center and humid air narrow the margin for over tickets, especially when both sides can produce swing-and-miss pockets. This matchup has plenty of strikeout texture and fewer easy multi-run bursts. Even with one or two solo shots, 7.5 can still land under."),
("Petco at night is already a run damper; with 65° air and wind blowing in from center, seven runs is a serious climb. The park’s marine layer and deep right-center lanes reward pitchers who stay above the barrel, and both staffs can do that. Unless defensive mistakes multiply, this game profiles as long at-bats and short rallies.",
"Petco at night asks offenses to be patient and precise, and the cool marine setup with wind in only strengthens that tax. Seven runs is a demanding target in this environment unless fielding errors open extra doors. The cleaner expectation is scattered offense and short rallies."),
("Seven and a half is modest for Dodger Stadium when both lineups are healthy enough to punish middle relievers. The 330-395-330 layout and light breeze out won’t create a launch-party game, but it does support steady scoring chances across nine innings. This over is about depth-on-depth plate appearances more than one crooked frame.",
"Seven and a half is light when both lineups can attack middle relief and avoid long dead zones. Dodger Stadium won’t play tiny tonight, but it should still provide enough carry and gap room for steady scoring pressure. This over is a depth wager, not a fireworks wager."),
("Target Field is fair tonight, not pitcher-hostile, and that keeps eight runs within normal range if either starter exits by the fifth. Both clubs bring active run producers, and the game can tilt over through doubles volume rather than home-run spikes. A 5-4 or 6-3 script is the most natural path.",
"Target Field is neutral enough to let lineup quality decide things, and eight is reachable if either starter turns it over early. Both offenses have active run producers who can build runs through doubles and situational contact. The likely over script is steady scoring, not a single blowup inning."),
("Sutter Health Park under lights plays closer to neutral, and tonight’s 64.8° air should keep carry in check despite a mild breeze out. With both clubs capable of empty innings when chase rates rise, this total can stay below nine without requiring dominance. The under path is fewer free baserunners and limited multi-run swings.",
"Under the lights in Sacramento, this park usually settles into neutral-to-slightly-muted scoring. Cooler evening air reduces cheap carry, and both offenses can disappear for stretches when expansion swings show up. Fewer free passes should keep this total under pressure."),
("In a roof-controlled game at American Family Field, the environment is predictable, and seven can hold when strike throwing sets the tone early. The park is not extreme either way, which helps quality pitching look cleaner than outdoors. This under is thin, but still playable on controlled conditions and expected contact suppression.",
"A roof game removes weather noise, which helps under tickets when both staffs can establish strikes early. American Family Field is balanced enough that disciplined pitching can keep run creation ordinary. This is not a wide edge, but seven still has a defensible under case."),
]
}

for fn,pairs in repls.items():
    p=base/fn
    text=p.read_text()
    matches=list(re.finditer(r'<p class="lede">.*?</p>', text, flags=re.S))
    if len(matches)!=len(pairs):
        raise SystemExit(f'{fn}: expected {len(pairs)} ledes, found {len(matches)}')
    out=[]
    last=0
    for m,(_old,new) in zip(matches,pairs):
        out.append(text[last:m.start()])
        out.append(f'<p class="lede">{new}</p>')
        last=m.end()
    out.append(text[last:])
    p.write_text(''.join(out))
    print(f'updated {fn}')
print('updated')
