from pathlib import Path
import re

files = {
    'sportzballz.io/2026-04-14.html': [
        "PNC Park asks a lineup to earn every loud out: 325 down the left line, 410 to dead center, 320 to right, and a crosswind that keeps carrying trouble into the gaps. Pittsburgh’s starter is built for that geometry, living at the knees and forcing Washington to string three clean swings in a row. With no fresh pregame injury scratches on the Pirates’ regulars, the home side has the sturdier path through innings six to eight.",
        "At Truist (335-400-325), warm air turns hard contact into quick damage, but this game still hinges on which club controls at-bat quality when traffic starts. Atlanta can stack disciplined plate appearances behind a healthy middle order, while Miami is still patching run production around a thinner bench due to lingering IL depth issues. In this weather, the favorite is the team less likely to donate empty innings.",
        "Comerica’s footprint—345 to left, 420 to center, 330 to right—rewards range and punishes impatient offense, even on a warm evening. Detroit’s defensive alignment and starter profile fit that map better, especially once the ball starts finding the alleys. With both clubs avoiding late injury surprises on the lineup card, the Tigers still bring the cleaner prevention game.",
        "Camden’s reshaped left side plus a 333-410-318 layout asks for complete offense, not just pull-side thunder, and Arizona is built for that style. In 80s heat with a light breeze toward center, first-to-third pressure becomes a real weapon over nine innings. Baltimore’s star power is obvious, but with no new Diamondbacks absences and better baserunning pressure, the dog has a credible edge.",
        "Busch Stadium (336-400-335) can look roomy until warm air and a firm wind turn medium fly balls into extra-base traffic. St. Louis has enough healthy right-left balance to keep Cleveland from matching up comfortably in the middle innings. In what should be a close game, the side with more practical ways to score from second base deserves the nod.",
        "Rate Field’s 330-400-335 dimensions and humid air usually reward pitchers who own the first pitch, and that profile tilts toward Tampa Bay tonight. The Rays can force bullpen decisions by the fifth with grindy at-bats, while Chicago is still managing around injury-related lineup thinness in key run-creation spots. This shapes up like a game Tampa controls by pressure, not fireworks.",
        "Petco at night—334 down left, 396 to center, 322 to right—shrinks cheap power and stretches every rally over one more good at-bat. Seattle’s starter works quickly enough to keep San Diego from settling into long counts, then hands off to a relief mix with defined roles. With no new Mariners scratches before first pitch and the Padres still shuffling depth pieces, the road side owns the cleaner script.",
        "Yankee Stadium’s 318-399-314 profile invites drama, but this matchup is really about who creates repeat traffic once the game gets to the bullpens. New York’s healthy core can pressure both corners and cash in with situational contact, especially in warm conditions with a mild push to center. If the innings stay leveraged late, the Yankees still have more trustworthy outs to record.",
        "Dodger Stadium (330-395-330) in cool evening air rarely gifts runs; it rewards depth, strike throwing, and defensive precision. Los Angeles checks all three boxes, starting with a frontline arm and continuing with a lineup that keeps passing difficult counts to the next hitter. The Mets are dangerous at the top, but without fresh Dodgers injury setbacks, the home roster has the stronger full-game spine.",
        "Under a roof at American Family Field (344-400-345), the variables are execution, contact quality, and bench flexibility—nothing else. Milwaukee’s lineup pressure and running game can disturb a veteran rhythm pitcher who prefers static innings. With the Brewers’ regulars available and Toronto still short on a bit of position-player depth from the injured list, the edge sits with motion and pressure.",
        "Target Field’s 339-403-328 dimensions create an honest test: convert strikes early, defend the alleys, and take the extra base when it appears. Minnesota’s healthy core, led by its center-field speed and gap power, is made for that assignment. Boston can score in bursts, but if there are no late lineup injury changes, the Twins’ cleaner defensive floor is worth plus money.",
        "Great American Ball Park (328-404-325) punishes even one loose inning, so the team with steadier strike efficiency matters more than usual. San Francisco’s pitching path is better equipped for that first six-inning test, and the defense behind it is less likely to give away ninety feet. Cincinnati’s offense is live, but with no new Giants injury losses, the visitor’s run-prevention shape is more reliable.",
        "In Sacramento, the temporary big-league setup plays close to 330 down the lines with center beyond 400, and the evening air tends to bring the park back toward neutral. Texas arrives with more certainty in the top third of the order and fewer open questions from recent knocks and day-to-day absences. In a near pick’em, cleaner lineup continuity and tighter late-inning options matter.",
        "Citizens Bank Park (329-401-330) in mid-80s warmth is a place where one missed spot can become two runs before anyone exhales. Philadelphia’s impact bats are present, and its starter offers a higher probability of six composed innings before the leverage arms take over. Chicago has punch, but with no new Phillies injury concerns pregame, the home side carries the safer scoring floor."
    ],
    'sportzballz.io/2026-04-14-plus-money.html': [
        "A good underdog ticket needs a believable baseball story, and Arizona has one at Camden’s 333-410-318 geometry: line drives into space, aggressive turns, and pressure on every relay throw. The warm forecast and center-field breeze add extra strain to command late in counts, which favors a club that runs and advances. With no late Diamondbacks injury scratches on the card, this price is still longer than it should be.",
        "St. Louis as a dog works because Busch (336-400-335) rewards complete offense on warm, windy nights, not just headline sluggers. The Cardinals can score with doubles, first-to-third reads, and matchup pressure once bullpens begin to mix. Cleveland is live, but with no fresh St. Louis health setbacks before first pitch, the plus number remains a buying spot.",
        "At Target Field (339-403-328), underdogs cash when they field cleanly, avoid free passes, and steal one extra base at the right time. Minnesota’s current lineup health gives it enough speed and two-strike contact to play that brand of game for nine innings. If Boston doesn’t get a blowup inning, this price on the Twins is still generous."
    ],
    'sportzballz.io/2026-04-14-run-totals.html': [
        "PNC is deep at 325-410-320, but warm air and a cross-breeze can turn ordinary contact into doubles chaos, cut-off throws, and crooked innings. This over is less about tape-measure homers and more about repeated traffic with runners in motion. With both clubs avoiding late injury scratches among key bats, 9.5 has room to clear.",
        "Great American’s 328-404-325 lines and warm conditions make every elevated fastball feel like a loaded decision. In this park, one command lapse can become three runs before the bullpen phone rings. Even at a healthy opener, the run environment still justifies an over look.",
        "Busch (336-400-335) carries a pitcher-friendly reputation until heat and a strong push to center wake up the middle of the yard. That weather turns warning-track balls into playable scoring chances and extends innings against middle relief. With regulars available on both sides, 8.5 is still a touch light.",
        "At Yankee Stadium (318-399-314), totals can climb on geometry alone, and warm air with a soft tailwind only widens the damage zone. You do not need perfect barrels here; you need steady traffic and one mistake to the short side. With both middle orders intact, this number has multiple over paths.",
        "Truist (335-400-325) in warm, dry conditions tends to run quickly once pitch counts rise and the fourth-best reliever enters earlier than planned. Atlanta can create that stress, and Miami has enough contact-speed pieces to answer late. This over is built on sequencing and pressure, not home-run luck.",
        "Citizens Bank Park’s 329-401-330 setup plus heat makes routine fly-ball management harder for both staffs. The dimensions reward pull authority, and the ball carries just enough to keep outfielders retreating. With both lineups mostly healthy, 9.5 remains playable.",
        "Comerica is huge at 345-420-330, but warm air and a wind nudge toward left can keep gap traffic alive all night. This total doesn’t require a slugfest; it needs doubles, baserunners, and one tiring inning from either starter. Over 7.59 is reachable on volume.",
        "Camden’s 333-410-318 look still suppresses some pull damage, yet 80s heat and a center-field breeze keep the rest of the yard active for run creation. Both clubs can score with pace—advancement, contact, and pressure—not just fence-clearing swings. That profile supports over 8.82.",
        "Rate Field (330-400-335) with humid air and two staffs capable of creating swing-and-miss pockets points to fewer sustained rallies. The under case is simple: more strikeouts, fewer multi-hit innings, and limited free baserunners. Even with a solo shot or two, 7.5 can stay below.",
        "Petco after dark (334-396-322) plus marine air and wind in from center is an old-fashioned under setting. Offenses often need three good swings to score one run here, and that’s a hard rhythm to sustain for nine innings. Seven is tight, but the environment still leans down.",
        "Dodger Stadium’s 330-395-330 geometry is fair rather than tiny, yet two deep lineups can still pull this game beyond 7.5 by attacking middle relief. The over case is cumulative: quality plate appearances in innings five through eight. If neither side carries fresh injury losses into first pitch, depth should create enough scoring volume.",
        "Target Field (339-403-328) sits in the balanced middle where lineup quality usually decides totals more than park tricks. Eight runs is attainable if either starter exits early and the game turns to middle-inning matchups. Both clubs have active run producers to keep the scoreboard moving.",
        "In Sacramento’s roughly 330-to-the-corners, 400-plus-to-center setup, a mild breeze to center can stretch innings when command drifts. This over is a traffic wager: singles into doubles, first-to-third pressure, and bullpen exposure by the sixth. At 8.59, that path is very live.",
        "A roof game at American Family Field (344-400-345) removes weather variance, which often helps an under when both staffs can get strike one. The park is fair, but disciplined sequencing can keep rallies to one run at a time. Seven is not huge, yet the game script still tilts under."
    ]
}

for path, repl in files.items():
    p = Path(path)
    text = p.read_text()
    pattern = re.compile(r'<p class="lede">.*?</p>', re.S)
    found = pattern.findall(text)
    if len(found) != len(repl):
        raise SystemExit(f"{path}: expected {len(repl)} ledes but found {len(found)}")
    i = [0]
    def sub(_):
        s = f'<p class="lede">{repl[i[0]]}</p>'
        i[0] += 1
        return s
    new_text = pattern.sub(sub, text)
    p.write_text(new_text)
    print(f"updated {path} ({len(repl)} ledes)")
