import re, html
from pathlib import Path

base = Path('/Users/asmith/.openclaw/workspace/sportzballz.io')

updates = {
'2026-04-14.html': {
'Pittsburgh Pirates over Washington Nationals': "Pittsburgh is the steadier side in a game shaped by PNC’s roomy alleys (325 to left, 410 to center, 320 to right) and a 13.7 mph crosswind that can turn hard contact into long outs. Mitch Keller’s sinker profile fits that geometry, while Washington still leans on streaky run creation. With both lineups posted and no late core absences flagged, the favorite has the cleaner nine-inning path.",
'Atlanta Braves over Miami Marlins': "At Truist (335-400-325), this plays like an Atlanta control game: enough carry in warm 81.7° air, but not enough wind to erase the pitching edge. Reynaldo López gets a Marlins lineup that can go quiet for stretches, and Atlanta’s middle-order health looks stable entering first pitch. Price is chalk, but the matchup logic is cleaner than the ticket cost.",
'Detroit Tigers over Kansas City Royals': "Comerica’s long corridors (345 down the left-field line, 412 to dead center, 330 to right) reward teams that manufacture extra bases and prevent the crooked inning. Detroit’s profile fits that better tonight, even in 81.8° weather with a crosswind that won’t consistently aid pull power. If lineups arrive without surprises, the Tigers’ run-prevention shape keeps them in front of this number.",
'Arizona Diamondbacks over Baltimore Orioles': "Camden Yards still asks right-handed power to work through deep left-center space, and that matters in a game expected to be decided by sequencing more than one swing. Arizona’s offense is healthier at the top and better built for doubles-and-pressure baseball, while 88.2° heat and a breeze to center add just enough volatility for a plus-money live dog. Kelly doesn’t need dominance here—just six composed innings.",
'St. Louis Cardinals over Cleveland Guardians': "Busch Stadium (336-400-335) with 15 mph wind pushing to center is a different place than its low-scoring reputation, especially in near-90° air. St. Louis has more ways to score in that environment, and its key bats are all available on the pregame board. In a near-pick’em game, the side with better damage potential in these conditions gets the nod.",
'Tampa Bay Rays over Chicago White Sox': "Rate Field’s broad center field (400 feet) and a damp crosswind setup favor pitchers who can miss barrels, and that points toward Tampa Bay behind McClanahan. Chicago’s young arms can flash stuff but still run high-stress counts, which is dangerous against a patient Rays order. Unless a late lineup scratch changes the top six hitters, this is Tampa’s matchup to control.",
'Seattle Mariners over San Diego Padres': "Petco’s dimensions (334-396-322) and marine night air already compress offense; add a 9.7 mph breeze blowing in from center and every run gets expensive. That setting favors Seattle’s style with Bryan Woo attacking the zone and forcing contact quality down. San Diego’s lineup uncertainty at publish time only strengthens the case for the steadier side.",
'New York Yankees over Los Angeles Angels': "Yankee Stadium can flip a game in one inning, but tonight’s edge is broader than the short porches (318 left, 314 right, 399 center). In 84.7° warmth with wind drifting out, New York still owns the superior run-creation floor, and its core bats are active. If this turns into a bullpen game by the sixth, the Yankees are better equipped to win the leverage outs.",
'Los Angeles Dodgers over New York Mets': "Dodger Stadium’s 330-395-330 frame and mild 62.6° evening usually reward complete rosters, not hopeful scripts. Los Angeles brings the deeper offense and the cleaner starter matchup, and the Mets’ path depends on near-perfect traffic management. With both lineups confirmed, the home side remains the higher-probability grind over nine innings.",
'Milwaukee Brewers over Toronto Blue Jays': "Inside American Family Field (344-400-345), weather noise drops and execution decides it. Milwaukee’s young power-speed mix plays well in that neutralized environment, and its active lineup board suggests no missing centerpiece bats. Against a veteran starter, the Brewers still project to create more pressure inning to inning.",
'Minnesota Twins over Boston Red Sox': "Target Field (339-403-328) in 64.5° air with only a light breeze to center should play fair, not explosive. That suits Minnesota, which can win with run prevention and timely extra-base contact rather than a home-run race. With Buxton and the core group available, the plus price is playable on structure alone.",
'San Francisco Giants over Cincinnati Reds': "Great American Ball Park is tight down the lines (328 and 325) and can get loud fast in 80° weather, but this handicap leans on starting-pitch quality more than park fear. San Francisco has the cleaner mound profile for the first two trips through the order, and that matters in a venue where early jams spiral quickly. If neither club loses a late bat, the Giants have the calmer path.",
'Texas Rangers over Athletics': "Sutter Health Park’s Sacramento layout (330-403-325) plays fairer at night, and 64.8° air with modest breeze out to center should keep the game from becoming a cheap-homer derby. Texas owns the stronger top-of-order on-paper and arrives with key regulars listed active. In a near-even market, that roster stability is enough to side Rangers.",
'Philadelphia Phillies over Chicago Cubs': "Citizens Bank Park (329-401-330) with 86.3° heat is built for carry, especially when mistakes leak to the pull gaps. Philadelphia’s lineup is healthy where it matters and better positioned to cash those mistakes than Chicago tonight. With Nola set to work at home, the Phillies hold the sharper run expectancy profile."
},
'2026-04-14-plus-money.html': {
'Arizona Diamondbacks over Baltimore Orioles': "Underdogs need a real map, and Arizona has one tonight: gap pressure in Camden’s deeper left-center, plus enough speed to turn singles into immediate stress. The 88.2° heat with breeze to center can flatten command late, which helps the side that strings contact instead of waiting for one blast. With the principal bats available, this dog is priced wider than the matchup warrants.",
'St. Louis Cardinals over Cleveland Guardians': "This is the kind of plus number worth taking—small edge, big weather assist. Busch is playing warm and wind-aided to center, which widens scoring paths for a Cardinals lineup that has its main run producers active. In a game expected to hinge on middle innings, that environment gives St. Louis a little more upside than the market implies.",
'Minnesota Twins over Boston Red Sox': "Target Field won’t gift many cheap runs tonight, so execution and bullpen shape matter more than brand name. Minnesota’s active core and cleaner defensive profile make them live at this price, especially in a game likely decided by one or two sequencing moments. If this stays in the eight-run neighborhood, the dog remains very much alive."
},
'2026-04-14-run-totals.html': {
'Pittsburgh Pirates vs Washington Nationals — OVER 9.5': "With 79° warmth and a 13.7 mph crosswind at PNC, this total leans over because contact should stay in play all night, forcing extra defensive chances. The park’s deep middle (410 feet) cuts some homers but also creates long run-scoring innings through doubles and first-to-third pressure. Both lineup cards are intact enough to support traffic rather than waiting on solo shots.",
'Atlanta Braves vs Miami Marlins — OVER 8.5': "Truist’s 335-400-325 dimensions plus dry, warm air make 8.5 a reachable number if either starter loses the zone once. Atlanta’s run creators are available, and Miami has enough athletic contact to contribute its share against the back half of the game. This projects as an over built on sustained baserunners, not miracle homers.",
'Detroit Tigers vs Kansas City Royals — UNDER 7.59': "Comerica is still one of the better under parks because of its deep power alleys and 412-foot center, and that geometry matters more than the warm temperature. Even with decent hitting conditions, many fly balls die into outs here, especially when both starters can work ahead. The under case is about limiting damage swings and forcing three-hit rallies.",
'St. Louis Cardinals vs Cleveland Guardians — OVER 8.5': "In Busch, 15 mph wind out to center and near-90° heat are enough to upgrade ordinary contact into warning-track trouble and occasional carry-outs. With both offenses showing full-strength top halves, 8.5 is a fair over number in this specific weather window. The forecasted run environment is more offensive than the stadium’s reputation.",
'Tampa Bay Rays vs Chicago White Sox — UNDER 7.5': "Rate Field’s larger center gap and a humid, crosswind night profile point to suppressed slug unless hitters square mistakes perfectly. Tampa and Chicago can both create strikeout-heavy stretches, which is exactly what under tickets need at this number. A couple of solo homers can happen and still leave this under live deep into the eighth.",
'Seattle Mariners vs San Diego Padres — UNDER 7.0': "Petco at night is already a run damper; with 65° air and wind blowing in from center, seven runs is a serious climb. The park’s marine layer and deep right-center lanes reward pitchers who stay above the barrel, and both staffs can do that. Unless defensive mistakes multiply, this game profiles as long at-bats and short rallies.",
'New York Yankees vs Los Angeles Angels — OVER 8.59': "Yankee Stadium’s short porches and warm 84.7° conditions usually put pressure on any total in the high eights, especially with wind nudging balls toward center. Even routine fly contact can become extra-base offense in this setup. With both clubs carrying active middle-order bats, this number leans over on park math and weather alone.",
'Los Angeles Dodgers vs New York Mets — OVER 7.5': "Seven and a half is modest for Dodger Stadium when both lineups are healthy enough to punish middle relievers. The 330-395-330 layout and light breeze out won’t create a launch-party game, but it does support steady scoring chances across nine innings. This over is about depth-on-depth plate appearances more than one crooked frame.",
'Minnesota Twins vs Boston Red Sox — OVER 8.0': "Target Field is fair tonight, not pitcher-hostile, and that keeps eight runs within normal range if either starter exits by the fifth. Both clubs bring active run producers, and the game can tilt over through doubles volume rather than home-run spikes. A 5-4 or 6-3 script is the most natural path.",
'San Francisco Giants vs Cincinnati Reds — OVER 9.18': "Great American’s compact lines (328 to left, 325 to right) are tailor-made for overs once temperatures rise into the 80s. Add the crosswind and this park turns medium contact into stressful innings quickly. With both offenses built to attack mistakes early in counts, the total still leans upward despite the already-high number.",
'Philadelphia Phillies vs Chicago Cubs — OVER 9.5': "Citizens Bank is a carry park in hot air, and 86.3° with breeze across to right keeps the ball lively all evening. The dimensions (329-401-330) reward pull-side authority from both lineups’ core hitters, all of whom are available. Ten runs is not a stretch in this weather-and-park combination.",
'Arizona Diamondbacks vs Baltimore Orioles — UNDER 8.82': "Camden’s remodeled left-field depth still steals extra-base damage from right-handed pull power, and that supports an under at this unusual number. Even in 88° weather, long fly balls can die in that part of the park before they become crooked innings. If starters avoid free passes, this total trends to a tighter scoring game than the heat suggests.",
'Milwaukee Brewers vs Toronto Blue Jays — UNDER 7.0': "In a roof-controlled game at American Family Field, the environment is predictable, and seven can hold when strike throwing sets the tone early. The park is not extreme either way, which helps quality pitching look cleaner than outdoors. This under is thin, but still playable on controlled conditions and expected contact suppression.",
'Texas Rangers vs Athletics — UNDER 8.55': "Sutter Health Park under lights plays closer to neutral, and tonight’s 64.8° air should keep carry in check despite a mild breeze out. With both clubs capable of empty innings when chase rates rise, this total can stay below nine without requiring dominance. The under path is fewer free baserunners and limited multi-run swings."
}
}

for file_name, file_updates in updates.items():
    path = base / file_name
    text = path.read_text()
    for h2, new_lede in file_updates.items():
        pattern = rf'(<h2>{re.escape(h2)}</h2>.*?<p class="lede">)(.*?)(</p>)'
        replacement = lambda m: m.group(1) + html.escape(new_lede, quote=False) + m.group(3)
        text, count = re.subn(pattern, replacement, text, flags=re.S)
        if count != 1:
            raise RuntimeError(f'Could not update {file_name} :: {h2} (count={count})')
    path.write_text(text)

print('done')
