import re, pathlib
base=pathlib.Path('/Users/asmith/.openclaw/workspace/sportzballz.io')
repls={
'2026-04-14.html':[
"Pittsburgh is the side because this game is built for contact management at PNC’s deep left-center gap (410 to center, 399 in the notch), and Keller’s heavy fastball profile usually survives there better than a fly-ball arm. With Bryan Reynolds and Brandon Lowe both listed active, the Pirates can pressure the middle innings, while Washington’s active-tag group still looks thinner behind CJ Abrams. Cool river air and a light cross-breeze should keep a few warning-track balls in play, which favors the steadier run-prevention club.",
"Atlanta gets the nod at Truist, where the 335-foot lines reward pull power but the roomy right-center (375) still demands complete at-bats, and that balance fits the Braves’ deeper top six. Austin Riley and Chris Sale are both listed active, while Miami’s active board is longer but less impact-heavy in the middle order. In mild Georgia humidity with only modest wind, this projects more as sustained traffic than one big inning, and Atlanta’s cleaner bullpen bridge is the separator.",
"Detroit is the play in Comerica’s vast outfield geometry (420 to dead center), a park that turns lazy extra-base hopes into long outs and rewards teams that defend and sequence runners. Framber Valdez’s ground-ball shape pairs with that layout, and with Colt Keith and Casey Mize listed active, the Tigers carry enough two-way stability. Kansas City still has Bobby Witt Jr. active and dangerous, but in cool evening air this matchup leans toward disciplined run suppression over fireworks.",
"Arizona profiles as live plus money because Camden’s 410-foot center and deep left-center alley reduce cheap damage and push the game toward execution over slug volume. Merrill Kelly’s strike-throwing style plays in that environment, and with Corbin Carroll and Gabriel Moreno active, the Diamondbacks can create pressure without waiting for a three-run shot. Baltimore’s lineup remains dangerous with Cowser and Mayo active, but in cool bay air the cleaner path still points to Arizona over nine innings.",
"St. Louis is a worthwhile dog in Busch, where 400 to center and broad power alleys reward line-drive continuity more than all-or-nothing swings. With Iván Herrera and Alec Burleson listed active, the Cardinals’ run-creation floor is better than the price implies, and their late-game pitching mix is less fragile than Cleveland’s on this slate. A cool St. Louis night with only a light breeze should keep scoring orderly, which helps the team with the steadier inning-to-inning structure.",
"Tampa Bay is the practical side at Rate Field: 400 to center and symmetric alleys punish sloppy contact, and McClanahan’s swing-and-miss profile travels well there. The Rays’ active list includes Drew Rasmussen and Chandler Simpson, giving them both length and speed options, while Chicago’s active board is more youth-driven around Colson Montgomery and Meidroth. With brisk April air likely muting carry, the edge sits with the club that converts more outs without defensive stress.",
"Seattle fits Petco’s script—marine air, big alleys (391 right-center), and long innings where command matters more than spectacle. Bryan Woo and Cal Raleigh are both listed active, and the Mariners’ announced lineup continuity should translate into better situational offense than San Diego can guarantee before full card confirmation. Even with Tatis active, this is the type of cool coastal night where one extra clean bullpen frame decides it, and Seattle is better built for that frame.",
"The Yankees are the side because Yankee Stadium’s short porches (318 left, 314 right) reward disciplined loft from a lineup that still has Aaron Judge and Cody Bellinger active. New York’s continuity is choppier than usual, but the top-end power and late reliever quality remain intact enough to justify the favorite tag. With mild Bronx temperatures and a manageable breeze, this sets up as a controlled scoring environment where the better top-third offense usually cashes first.",
"Los Angeles is still the right read at Dodger Stadium, where the 375-foot gaps and 400-foot center neutralize panic swings and reward complete roster depth. Yamamoto’s command profile plus an active Dodgers core (Pages, Vesia, Treinen all listed) gives them more avenues through seven innings than the Mets currently show. New York’s active group has talent, but with cooler late-night air in Chavez Ravine, run creation tends to arrive by patience and sequencing, not chaos, and that leans Dodgers.",
"Milwaukee has the cleaner case under a roof-capable park where weather volatility is mostly removed and execution stands alone. American Family Field’s dimensions (roughly 344 down the lines, 400 to center) still reward balanced contact, and with Brice Turang and Brandon Woodruff listed active, the Brewers bring both table-setting and pitching structure. Toronto’s active names include Daulton Varsho and Andrés Giménez, but this matchup favors the side with fewer defensive leak points over nine innings.",
"Minnesota offers fair plus value at Target Field, where 404 to center and cool spring nights often turn loud contact into playable balls. Byron Buxton and Brooks Lee are listed active, giving the Twins enough athletic coverage and speed to win the extra-90-foot game, while Boston’s active core remains dangerous but slightly more dependent on gap damage. With a likely upper-40s to low-50s first pitch and modest wind, this projects tight, and plus money on the cleaner run-prevention path is justified.",
"San Francisco gets the edge in Cincinnati despite the park’s small dimensions (328 to left, 325 to right) because this matchup is more about pitcher shape than raw fence distance. Robbie Ray’s miss potential gives the Giants a route through the Reds’ top order, and with Harrison Bader and Casey Schmitt active they can defend the alleys behind him. Warmth could wake the ball a bit at Great American, but the better strikeout-and-contact mix still points toward San Francisco.",
"Texas is the side in Sacramento’s Sutter Health Park profile, where the compact corners and open-air carry can create crooked innings unless staffs stay ahead in counts. Corey Seager and Evan Carter are listed active, and that top-half quality gives the Rangers more reliable run manufacturing than the Athletics’ current construction. With mild evening air and no severe wind flag, this reads as a game won by lineup depth and late leverage pitching, both favoring Texas.",
"Philadelphia makes sense at Citizens Bank, where 329 to left and 330 to right invite pull power but still demand strike-throwing in leverage spots. With Bryce Harper and Aaron Nola active, the Phillies own both the thunder and the stabilizer, while Chicago’s active group has talent yet less certainty in run-prevention sequencing. If a light breeze drifts toward right, it helps both clubs, but the better ninth-inning pathway still belongs to Philadelphia."
],
'2026-04-14-plus-money.html':[
"Arizona at plus money is worth the swing because Camden’s deeper left-center corridor reduces random homers and pushes the game toward command, defense, and baserunning precision. With Corbin Carroll and Gabriel Moreno active, the Diamondbacks can manufacture pressure without waiting on one blast, and Merrill Kelly’s profile is built for that runway. Baltimore is dangerous, but in cool harbor air the underdog with the cleaner inning-to-inning process is playable.",
"St. Louis as a small dog is justified by park fit and roster shape: Busch’s big center field rewards clubs that string quality at-bats and avoid free passes. Iván Herrera and Alec Burleson being active keeps the Cardinals’ middle sturdy, and their relief options project steadier once this turns into a one-run game. Cleveland can absolutely win it, but the price underrates St. Louis’s probability in a low-variance environment.",
"Minnesota plus money is a pragmatic buy in April at Target Field, where big dimensions and cool air often flatten raw power edges. Buxton and Brooks Lee are active, which improves both run prevention and first-to-third pressure, and that matters in tight totals windows. Boston’s lineup quality is real, yet this setup favors the team that can win with defense and bullpen sequencing, giving the dog legitimate value."
],
'2026-04-14-run-totals.html':[
"Play the OVER 8.9 in Pittsburgh–Washington because PNC’s spacious gaps create doubles-and-triples pathways when contact quality is high, and both clubs can stack that type of contact even without a home-run parade. The Pirates’ active core around Reynolds and Lowe raises baseline run creation, while Washington’s active table-setters keep pressure on innings two through six. Even in cool river air, sustained traffic points to enough scoring events to clear this number.",
"OVER 8.4 in Atlanta–Miami is the right lane: Truist’s short lines plus humid spring conditions often turn medium contact into damage, and both offenses carry active middle-order bats. The Braves’ active group with Riley available supports multi-run bursts, while Miami’s active depth can answer against second-time-through pitching. This total is low enough that two productive innings per side can put it in danger quickly.",
"OVER 8.45 in St. Louis–Cleveland works because Busch suppresses pure homer chaos but still rewards line-drive chains and opposite-field contact, exactly how both lineups are currently constructed. Active bats like Herrera for St. Louis and Naylor/Hedges depth for Cleveland raise the probability of extended innings. With no severe weather drag expected, the path to nine runs is realistic through accumulation rather than one swing.",
"OVER 8.5 in Yankees–Angels is a park-and-profile call: in Yankee Stadium, 314 to right and 318 to left can convert routine fly balls into immediate offense when pull hitters are healthy. Judge and Bellinger active for New York, plus active Angels run producers, create scoring upside on both sides. If the Bronx breeze stays modest, this still clears through bullpen exposure in the late innings.",
"OVER 8.0 in Twins–Red Sox is attractive because the number leaves little room for normal variance once both lineups get three trips through. Target Field is big, but active speed and gap hitters—Buxton for Minnesota, Rafaela for Boston—create extra-base pressure without perfect launch angles. Cool weather may trim one homer, yet the overall baserunner volume supports nine or more total runs.",
"OVER 8.95 in Giants–Reds is a geometry play at Great American: short corners and a lively carry window can erase pitcher advantages once mistakes leak up in the zone. Even with quality arms, active hitters like Elly De La Cruz and Harrison Bader profiles can create fast swings in run expectancy. This number is high for a reason, but park context still justifies expecting double-digit scoring threats.",
"OVER 9.5 in Phillies–Cubs makes sense in Citizens Bank Park, where compact power alleys reward left-right balance and punish thin bullpen depth. Harper and Bohm active for Philadelphia, plus Chicago’s active top-half bats, creates enough hard-contact potential to challenge ten. A neutral-to-light wind does not need to help much here; normal park behavior can carry this over.",
"OVER 8.5 in Diamondbacks–Orioles is supported by lineup quality on both sides and Camden’s modern shape, which still allows doubles volume even when home runs are moderated. Carroll and Moreno active for Arizona plus Baltimore’s active young core means there are few soft pockets in either order. In cool but playable conditions, continuous baserunners are enough to reach nine.",
"UNDER 7.5 in Tigers–Royals is the disciplined side because Comerica’s 420-foot center and expansive alleys suppress quick crooked numbers, especially on cool nights. With both clubs carrying active defensive pieces and front-line starters capable of weak contact, run creation should come slowly. Unless command collapses early, this profiles as a 3-2 or 4-2 type script.",
"OVER 7.5 in Rays–White Sox is playable despite a fair pitching matchup because the total is modest and both clubs can score through sequencing, not just homers. Rate Field does not need heat to produce offense if runners are in motion, and active bats plus active bullpen usage risk can open late runs. Eight is a reachable target in this setup.",
"UNDER 7.0 in Mariners–Padres is the sharper expectation at Petco, where marine-layer nights and deep gaps historically tax power output. With Woo and King profiles built on command and strikeout ability, plus active defensive catchers, base traffic should be limited. A 3-2 finish is more plausible than an extended slugfest.",
"UNDER 7.5 in Dodgers–Mets is justified by late-night Dodger Stadium run suppression and two staffs that can miss bats when ahead in counts. Even with active stars on both cards, the cooler Chavez Ravine air and roomy gaps reduce easy homers. This total asks for sustained rallies, and the pitching depth on both sides makes that a harder path.",
"UNDER 7.0 in Brewers–Blue Jays fits a roof-controlled game where weather can’t inflate carry and both starters can work deep when efficient. American Family Field’s dimensions are fair, but with active defenders and strong strike-throwing profiles, scoring windows may be brief. At this number every empty inning matters, and there should be plenty.",
"UNDER 8.5 in Rangers–Athletics lines up with expected game flow: even in a park that can play lively, both clubs have enough active bullpen arms to shrink late scoring once leverage begins. Seager and company can score, but the Athletics’ active pitching depth should prevent a runaway script. Nine is possible, but the median outcome lands just below."
]
}
for fn, arr in repls.items():
    p=base/fn
    s=p.read_text()
    pat=re.compile(r'(<p class="lede">)(.*?)(</p>)', re.S)
    i=[0]
    def sub(m):
        idx=i[0]
        if idx>=len(arr):
            return m.group(0)
        i[0]+=1
        return m.group(1)+arr[idx]+m.group(3)
    ns=pat.sub(sub,s)
    count=len(pat.findall(s))
    if i[0]!=len(arr) or count!=len(arr):
        raise SystemExit(f'mismatch {fn}: found {count}, replaced {i[0]}, expected {len(arr)}')
    p.write_text(ns)
    print('updated',fn,i[0])
