import re
from pathlib import Path

base = Path('/Users/asmith/.openclaw/workspace/sportzballz.io')

updates = {
'2026-04-14.html': [
"Pittsburgh is the right side because this park asks you to earn every long ball—about 325 down the line, 399 to left-center, and that deep 410 notch in left-center turns loud contact into long outs. With Keller’s heavy fastball profile built for big outfields and Washington arriving with a lineup that has been shuffled recently, the home club has the cleaner path through the middle innings. The weather feed is blank tonight, so the handicap leans on park geometry and roster continuity; with Bryan Reynolds and the core regulars active, Pittsburgh’s run creation floor still looks sturdier than the Nationals’.",
"Atlanta gets the nod in a park that can play small when the air gets warm—335 to left, 375 to left-center, and 400 to dead center reward lifted pull-side contact. López has the better support structure behind him and Miami’s margin narrows if its contact bats don’t string traffic early against a deeper Braves lineup. Even with live weather unavailable at publish, the injury sheet matters: Riley and Sale being active supports both lineup length and late-game run prevention, which is usually the difference in this price range.",
"Detroit is the side because Comerica’s spacious alleys—345 to left, 370 to left-center, and 420 to center—tend to mute one-swing innings and favor the club that can defend and run the bases cleanly. In a Valdez-Ragans duel, that extra outfield acreage raises the value of soft-contact management and bullpen sequencing, both areas where the Tigers profile steadier at home. With lineups still pending and weather not posted, the injury report showing Witt Jr. and Ragans active keeps Kansas City live, but Detroit’s broader two-way stability still makes it the more reliable ticket.",
"Arizona is the plus-money side because Camden’s remodeled left-field wall still suppresses cheap right-handed pull power, while the shorter right-field line (about 318) gives balanced lineups a chance to manufacture offense in multiple ways. Kelly’s pitch mix and tempo generally travel, and the Diamondbacks’ active core—Carroll, Moreno, Perdomo—keeps pressure on every base/out state. Weather is unavailable in the feed, so the argument leans on roster health and park fit; at this price, Arizona owns the better value lane.",
"St. Louis at home is playable because Busch (336 left, 375 left-center, 400 center) rewards disciplined at-bats more than pure launch-angle hunting, and that suits the Cardinals’ contact-to-power blend. McGreevy doesn’t need to dominate if he avoids free passes and lets the park hold damage to singles and doubles. With both lineups posted and key bats active on each side, the edge comes from the Cardinals’ cleaner path to six competitive innings before handing the game to a bullpen that has looked less volatile lately.",
"Tampa Bay is the side in Chicago because this matchup looks like a starter-and-command game first, and McClanahan’s strike-throwing ceiling still creates the highest-quality outs on the board. Rate Field can play homer-friendly to the pull gaps, but the Rays’ lineup construction is better equipped to cash runners once traffic starts. Weather and umpire data are missing, so the lean leans on personnel: with the Rays’ key contributors active and the White Sox still carrying a thinner error margin, Tampa has the more repeatable win script.",
"Seattle is the road favorite worth backing because Petco’s roomy dimensions—roughly 334 to left, 390 to left-center, and 396 to center—reward teams that pitch to contact quality and defend the alleys. Woo’s shape plays in that run environment, and the Mariners’ announced lineup continuity matters in a game likely decided in two innings, not nine. With weather unavailable and San Diego’s lineup still pending at publish, Seattle owns the clearer pregame picture and the safer late-inning path.",
"The Yankees are still the right side because Yankee Stadium’s short porch in right (314) changes game theory: one lifted left-handed swing can erase a quiet first five innings. New York’s lineup depth gives them more ways to force Detmers into high-stress counts, and their active star power raises the probability of a crooked inning even without sustained rallies. Weather data is missing, but with both lineups confirmed and Judge/Bellinger active, the home side carries the stronger run-scoring ceiling and bullpen bridge.",
"Los Angeles is the pick, but with discipline: Dodger Stadium’s 330-375-400 footprint and heavier night air often turn this into a sequencing game rather than a slugfest. Yamamoto’s command profile plus a steadier Dodgers defensive baseline creates fewer free bases, while the Mets have looked more dependent on timely damage than sustained pressure. Weather and crew data are absent, yet lineup continuity and healthier top-end talent still point to the Dodgers as the side with the better nine-inning floor.",
"Milwaukee earns the nod in a controlled environment where roof status can flatten weather noise and push the game toward execution details. American Family Field’s friendly power alleys reward well-timed aggression, but Misiorowski’s raw stuff and the Brewers’ speed-to-contact mix give them more paths to create separation than Toronto if this stays close late. With lineups not yet posted, the injury sheet showing Turang and Woodruff active strengthens Milwaukee’s all-around profile enough to justify the price.",
"Minnesota as a home dog is sensible because Target Field (339 to left, 377 left-center, 411 center) can suppress cheap pull power and reward gap-to-gap offense plus defensive range. In a game with both lineups posted, the Twins’ active core and steadier recent run-prevention structure make them live in every inning band, especially once bullpens take over. Weather is unavailable in the feed, but the park context and healthier lineup spine justify taking the plus number.",
"San Francisco is a pragmatic road side even in a hitter’s park because Great American’s cozy dimensions (328 left, 379 left-center, 404 center, 325 right) also punish command lapses, and Ray has shown the better ability to miss bats when leverage rises. Cincinnati’s upside is real with De La Cruz active, but this setup favors the club less likely to hand out free runners. With weather unposted and lineups pending, the Giants’ steadier run-prevention profile carries more weight than the venue’s volatility.",
"Texas is the pick because Sutter Health Park can play jumpy in April, and that increases the value of clean strike-throwing and outfield defense over pure power projection. Gore against Springs sets up as a game of who controls traffic first; the Rangers’ deeper active lineup, with Seager and Carter available, gives them better odds to convert those early baserunners. Weather data is absent, so roster quality and bullpen dependability become the tie-breakers, and both lean Texas.",
"Philadelphia is the side because Citizens Bank Park (329 left, 374 left-center, 401 center, 330 right) rewards decisive pull-side power, and the Phillies’ active core is built to cash that trait fast. Nola’s home command profile usually limits the big inning, forcing opponents to string multiple quality at-bats together—a harder ask for a Cubs lineup still searching for consistency. With weather missing from the feed, the call leans on known park behavior, lineup health, and a stronger late-game bullpen script for Philadelphia."
],
'2026-04-14-plus-money.html': [
"At plus money, Arizona is attractive because Camden’s deeper left-center geometry takes some bite out of Baltimore’s easiest power lane and shifts value toward balanced offenses. Kelly’s tempo and command can survive this park, and Arizona’s active top-to-middle core gives them enough contact quality to capitalize on any Trevor Rogers command drift. Weather is unavailable, so the edge is built on park fit, lineup health, and the underdog number being richer than the gap between these clubs.",
"St. Louis at plus odds is the kind of home dog worth a second look: Busch keeps games honest, rewards defensive positioning, and lowers the payoff on one-swing chaos. McGreevy doesn’t need dominance if he gets strike one and lets the Cardinals’ active infield convert contact into outs. With both lineups posted and the Guardians carrying a narrower offensive margin on the road, the Cardinals have the better value profile at this price.",
"Minnesota plus money works because Target Field stretches out center and the left-center alley, which quietly favors teams with gap power, rangy outfield defense, and patience late in counts. With Buxton and the Twins’ regular spine active, their path to pressure innings is wider than the market implies against a quality but less forgiving Boston run-prevention setup. Weather feed is missing, so this ticket leans on park dimensions, roster availability, and a price that overstates the separation."
],
'2026-04-14-run-totals.html': [
"Over 8.9 fits Pittsburgh-Washington because even in a deep park, both staffs can run up pitch counts early and expose middle relief before the seventh. PNC’s big left-center gap creates extra doubles and first-to-third pressure when outfield routes are tested, and both active lineups carry enough contact bats to keep the line moving. With weather unavailable, I’m weighting bullpen workload and defensive stress over wind assumptions.",
"Over 8.4 in Atlanta-Miami is justified by park shape and lineup depth: Truist can turn elevated contact into fast runs, especially once starters reach the third-time-through decision point. The Braves’ active middle order can force Meyer into traffic, and Miami has enough speed to answer against any shaky bullpen bridge. Even without live weather, this number leaves room for both clubs to contribute by the sixth.",
"Over 8.45 in St. Louis-Cleveland is a measured over, not a blind one: Busch suppresses cheap homers but still yields scoring when both teams can string quality plate appearances. With both lineups posted and key regulars active, this projects as a game where bullpens enter with men on base rather than clean innings. That sequencing risk supports the over at a total still below the common late-game swing range.",
"Over 8.5 in Yankees-Angels aligns with stadium physics and lineup construction: at 314 to right, one lifted lefty swing can accelerate scoring pace in a hurry. Both clubs have active bats capable of creating two-run innings without needing three hits, and the total is reachable even if one starter is sharp early. Weather feed is missing, so the short-porch run environment is doing the heavy analytical lifting.",
"Over 8.0 in Twins-Red Sox is playable because this number sits at a threshold where one bullpen wobble can decide the ticket. Target Field is not a pure launching pad, but its alleys reward line-drive offenses and defensive pressure, which both active lineups can generate. With weather unavailable, the better case is game-state volatility: enough on-base skill on both sides to create crooked innings late.",
"Over 8.95 in Giants-Reds is straightforward: Great American is small to both lines and unforgiving on fly-ball command mistakes. Even solid starting pitching can unravel with one mislocated fastball and two baserunners, and both active rosters have hitters who can convert that instantly. Weather isn’t posted, but this park’s dimensions alone keep nine runs firmly in range.",
"Over 9.5 in Phillies-Cubs is aggressive but defensible because Citizens Bank compresses foul territory impact and rewards pulled contact to both corners. Philadelphia’s active power core can do most of the lifting, while Chicago’s lineup has enough depth to force bullpen exposure by the middle frames. With weather data missing, this is still a park-and-personnel over where late leverage innings can add quick insurance runs.",
"Over 8.5 in Arizona-Baltimore works as a balance play: Camden’s left-field changes trimmed some easy homers, but both offenses still profile to create extra-base traffic to the gaps. With Carroll and Baltimore’s young core active, this game can score via doubles chains as much as home runs. Absent weather inputs, lineup health plus mid-range total pricing make the over the better side.",
"Under 7.5 in Detroit-Kansas City is the right lean for a park that stretches power alleys and rewards pitchers who keep contact off the barrel. Comerica’s dimensions turn many near-miss drives into warning-track outs, and both projected starters can work deep enough to avoid the weakest bullpen pockets. Even without weather data, the run-suppression geometry supports a lower-scoring script.",
"Over 7.5 in Rays-White Sox is a low-bar over where one uneven inning can cash half the work. Rate Field can play quick to the pull zones, and both active lineups have enough leverage bats to punish middle-relief mistakes. With weather unavailable, the value comes from the modest number and the likelihood that at least one starter exits before fully stabilizing.",
"Under 7.0 in Mariners-Padres tracks with Petco’s run environment and two staffs built to miss bats in leverage spots. The deep power alleys and heavier night conditions usually demand sustained rallies rather than single swings, and both active bullpens are equipped to strand inherited runners. Weather feed is blank, but park dimensions and pitching quality still make seven a fair ceiling target.",
"Under 7.5 in Dodgers-Mets makes sense because Dodger Stadium at night often plays bigger than the listed dimensions suggest, especially when command-first starters set the tone. With both lineups active, run production is still likely to come in pockets rather than waves, which favors the under if early walks are limited. Without weather specifics, this is primarily a pitcher quality and late-inning matchup call.",
"Under 7.0 in Brewers-Blue Jays is grounded in game control: roof-influenced environments reduce wind noise, and both teams can lean on strikeout-capable arms to escape traffic. American Family Field can still give up homers, but the number expects constant baserunners, and that’s harder to sustain against these active pitching groups. In a weather-neutral setup, execution favors the under.",
"Under 8.5 in Rangers-Athletics is a value under because this total prices in more clean offense than either side consistently produces against competent command. Sutter Health Park can boost offense in spurts, but both active lineups are more streaky than steady inning to inning, and that matters over nine frames. With weather unavailable, I’ll trust pitching depth and scoring volatility to stay mostly contained."
]
}

for fname, ledes in updates.items():
    path = base / fname
    text = path.read_text()
    matches = list(re.finditer(r'<p class="lede">.*?</p>', text, flags=re.S))
    if len(matches) != len(ledes):
        raise RuntimeError(f'{fname}: expected {len(ledes)} ledes, found {len(matches)}')

    out = []
    pos = 0
    for m, lede in zip(matches, ledes):
        out.append(text[pos:m.start()])
        out.append(f'<p class="lede">{lede}</p>')
        pos = m.end()
    out.append(text[pos:])
    path.write_text(''.join(out))
    print(f'updated {fname}: {len(ledes)} ledes')
