from pathlib import Path
import re

base = Path('/Users/asmith/.openclaw/workspace/sportzballz.io')

replacements = {
'2026-04-14.html': [
"Pittsburgh is the side because this park can turn ordinary contact into extra ninety feet when the air is this warm and the breeze is riding toward left. Keller’s heavy fastball profile plays better over full turns than a Nationals staff that has had to patch late innings lately, and Washington’s travel-weary bats still look thin in the middle. With no major pregame scratches among the core Pirate hitters, the cleaner nine-inning path points home.",
"In Atlanta tonight, the geometry and weather both lean toward hard contact carrying: 335 down the lines, gaps that reward line drives, and dry warmth that keeps the ball lively. López gets the nod over Meyer on command depth, and the Braves’ healthier top half is less vulnerable to one bad inning than Miami’s thinner run-creation pockets. This is less about fireworks and more about who can keep pressure on every frame.",
"Comerica’s deep center usually mutes cheap homers, but a firm wind to left reshapes the map for right-handed pull damage and keeps this from becoming a pure pitcher’s duel. Detroit’s lineup continuity is steadier tonight, while Kansas City comes in with a more shuffled look and less cushion if Ragans exits early. In a park where doubles decide games, the Tigers profile cleaner inning to inning.",
"Camden now asks for real pull authority to clear left, and that helps a road dog with disciplined gap hitting more than it hurts. Kelly has the veteran habit of shrinking innings before they spread, while Baltimore’s recent injury sheet and bullpen usage leave narrower margins after the sixth. Add heat and a mild jet to center, and Arizona has enough ways to steal this without needing a slugfest.",
"Busch on a warm night with wind to left is friendlier than its reputation, but it still rewards staffs that avoid free passes and clubs that run the bases cleanly. St. Louis gets that edge here, plus a lineup that holds its shape even with minor availability noise around the bench. Cleveland can absolutely win this game, yet the Cardinals own the tidier script from first pitch through matchup bullpen lanes.",
"Rate Field is open and noisy in this kind of wind, but a strong push in from left can knock down the ball that usually leaves in April. That suits Tampa Bay’s contact-and-speed pressure more than Chicago’s need for loft, and McClanahan’s floor is sturdier if conditions turn each inning into three singles instead of one swing. With no late injury surprise among Tampa’s core, the Rays are the practical side.",
"Petco at night is still a geometry problem for hitters: roomy alleys, heavier marine air, and less carry when the breeze works in from right. Woo’s strike-throwing profile fits that landscape, and Seattle’s defense behind him has been cleaner on first-step plays than San Diego’s recent version. If this stays tight through seven, the Mariners’ run-prevention shape is the better bet.",
"Yankee Stadium always tempts you into one-story analysis about the short porch, but this matchup is more complete than that. The Angels can damage mistakes, yet New York arrives with a deeper healthy core and more ways to score when the long ball doesn’t show. With mild outflow to left and no critical scratches, the Yankees have the broader lane across nine innings.",
"Dodger Stadium in this temperature band plays fair early and suppressive late, so the side often belongs to the club that prevents the crooked inning before the bullpen gates open. Yamamoto gives Los Angeles that stability, and the Mets’ current availability picture still leaves stress points in high-leverage bench and relief slots. The Dodgers are not just favored; they are structurally harder to beat tonight.",
"Under the Milwaukee roof, randomness from wind disappears and the game is decided by strike-throwing, depth, and traffic management. Misiorowski’s power profile can miss bats even against patient lineups, and the Brewers’ healthy position-player mix gives them multiple run paths against Gausman if his splitter sits up. In a controlled environment, Milwaukee’s flexibility is worth backing.",
"Target Field can be a chessboard when temperatures sit in the mid-60s: enough carry to punish mistakes, not enough to erase command lapses. Minnesota’s lineup balance against right-handed sequencing gives them a live underdog shot, especially if Abel keeps the first inning quiet and hands clean leverage to a rested back end. Boston’s talent is obvious, but the Twins’ home context closes the gap.",
"Great American is small in all the dangerous places, yet a firm breeze coming in from left can flatten one of Cincinnati’s usual advantage lanes. Robbie Ray’s north-south shape plays better in that weather than Singer’s contact profile if command wobbles, and the Reds’ recent availability churn leaves less margin for a comeback script. San Francisco doesn’t need domination here—just cleaner leverage innings.",
"At Sutter Health Park, the odd dimensions and warm twilight tend to create extra-base chaos, so the better side is often the club that can survive the weird inning. Texas brings steadier infield conversion and a deeper relief bridge, while the A’s still carry health and depth volatility around late-game matchups. In this park, stability is currency, and the Rangers have more of it.",
"Citizens Bank with 85-degree air and breeze to center is a run-producing setting, but it still rewards starters who get ahead and force chase above the zone. Nola’s command foundation gives Philadelphia the cleaner first six, and the Phillies’ core bats are intact enough to keep pressure on Chicago’s thinner middle relief. In a lively park, the better-prepared staff usually decides it, and that points Phillies."
],
'2026-04-14-plus-money.html': [
"This is the kind of Camden night where an underdog can script a win without outslugging anyone: hot air, modest outflow, and roomy left-center demanding real execution. Arizona’s lineup shape is intact, Kelly is built for traffic management, and Baltimore’s current availability picture still asks too much of the middle innings. At plus money, that combination is playable.",
"The Cardinals don’t need a perfect game to justify this number, only a cleaner one. Busch’s dimensions reward doubles and sequencing more than brute force, and St. Louis has enough healthy contact bats to keep Cleveland from settling into predictable leverage. With warm air and a leftward breeze, a one-run underdog path is very real.",
"Target Field offers Minnesota just enough environmental help—moderate carry to right, cool enough air to keep fly-ball damage honest. The Twins’ defensive shape and bullpen handoffs are in better order than this price implies, and their injury report does not remove key run producers. As a plus side at home, this is a logical value stab rather than a longshot fling."
],
'2026-04-14-run-totals.html': [
"At PNC, a warm evening with wind toward left can turn warning-track contact into scoring traffic. With two staffs likely to expose middle relief before the ninth, and dimensions that reward gap-to-gap doubles as much as homers, this total leans over on run environment plus bullpen shape.",
"Busch is usually moderate, but 87-degree air and a hard push to left alter the carry profile. Both lineups can string contact, neither starter is immune to third-time-through stress, and the game state projects enough baserunners to push this above the listed number.",
"Yankee Stadium plus warm air plus breeze to left is a familiar over recipe even before you account for two offenses with top-end pull power. The short right-field geometry remains a constant late-game equalizer, and neither bullpen enters spotless, so nine runs is a reachable runway.",
"Citizens Bank is compact where damage happens, especially to left-center, and this weather keeps balls moving. With two lineups that can punish mistakes in the middle innings and a park that converts lifted contact quickly, the over has a practical path rather than a parlay dream.",
"Truist in dry low-humidity warmth tends to play quick for hitters once starters miss arm-side. Add steady outflow to left and bullpens that may need four-plus outs from secondary arms, and this projects as a game where 5-4 is more likely than 3-2.",
"Camden’s deeper left field reduced cheap home runs, but hot air and wind to center reopen scoring routes via line drives and opposite-field carry. With both clubs carrying enough healthy middle-order bats and average command risk in the projected middle innings, the over grade is justified.",
"Comerica’s huge center keeps totals honest, yet wind to left and aggressive baserunning can manufacture runs without three true outcomes. If either starter loses fastball edge by the second turn, the spacious alleys become doubles factories, which supports an over even in a nominal pitcher park.",
"Petco under night conditions still suppresses carry, and the in-blowing right-field breeze tightens it further. With two starters capable of strike efficiency and a run environment that punishes high fly balls, seven is a fair under look if early defense is clean.",
"Dodger Stadium at this temperature usually plays neutral-to-slightly live early, then steadies as evening air settles. With two deep lineups and enough bullpen volatility on both sides to create one crooked frame late, the over is a thin but reasonable lean.",
"Target Field’s moderate outflow to right gives left-handed pull bats extra life, and both clubs can stack those plate appearances. Given ordinary middle-relief stability on each side, this number can clear through sequencing and doubles even without a home-run barrage.",
"Rate Field with warm air often screams over, but a strong wind in from left suppresses one of the park’s easiest damage lanes. Pair that with two starters who can miss bats in key spots and an under becomes the more disciplined read despite the temperature.",
"Great American is compact enough that even in-blowing wind doesn’t erase run volatility; it just changes how runs arrive. Singles-plus-gaps scoring, quick innings flips, and vulnerable bridge relievers keep this game pointed toward an over number in the high-eights.",
"Sutter Health Park’s unusual dimensions and lively bounces create extra baserunners beyond pure hit quality. Even with decent starting stuff on paper, this environment tends to tax command and defense over nine innings, making an over at this total the sensible side.",
"With the roof likely controlling conditions in Milwaukee, this total is less weather and more run-prevention architecture. Two starters with swing-and-miss ability, cleaner defensive conversion, and a park that doesn’t gift carry support an under if walks stay in check."
]
}

for fn, new_ledes in replacements.items():
    p = base / fn
    text = p.read_text()
    pattern = re.compile(r'<p class="lede">.*?</p>', re.S)
    old = pattern.findall(text)
    if len(old) != len(new_ledes):
        raise SystemExit(f'{fn}: expected {len(new_ledes)} ledes but found {len(old)}')
    for o, n in zip(old, new_ledes):
        text = text.replace(o, f'<p class="lede">{n}</p>', 1)
    p.write_text(text)
    print(f'updated {fn} ({len(new_ledes)} ledes)')
