import re
from pathlib import Path

base = Path('/Users/asmith/.openclaw/workspace/sportzballz.io')

repls = {
'2026-04-14.html':[
"The pick is Pittsburgh at -179, and the shape of the game fits that price. PNC plays quirky but fair—about 325 down the left-field line, 410 to center, and 320 to right—and tonight’s 79° air with a 13 mph push toward left gives hard contact a little extra carry in the pull lane. Keller’s steadier strike-throwing profile is the cleaner fit for this park geometry than Mikolas if traffic builds early. With Bryan Reynolds and Brandon Lowe available for Pittsburgh, and Washington still leaning on a mixed-availability core around CJ Abrams and Brady House, the deeper middle innings still point home side.",
"Houston at -179 is a chalk position with practical support, not just a number on a board. With the roof closed at Daikin Park, run conditions stay controlled: no wind randomness, familiar backdrop, and dimensions that reward true barrels (about 315 to left, 409 to center, 326 to right). That setting typically helps the club with the cleaner contact plan and fewer free baserunners, which has been Houston’s edge in this matchup profile. Brice Matthews and Bryan Abreu being available keeps both lineup length and late leverage intact, while Colorado’s group remains more volatile behind Senzatela over multiple turns.",
"St. Louis as a +102 dog is the kind of underdog worth taking because the game context gives them more than one winning script. Busch is spacious in the alleys (roughly 375 both gaps, 400 to center), but 87° heat with 14 mph out to left shrinks that space for right-handed pull damage. McGreevy’s contact management plays if he gets early count strikes, and the Cardinals can pressure Cantillo with a right-heavy sequence that matches the wind lane. With Burleson and Pallante available, the home club has enough depth to absorb volatility, while Cleveland’s active list around Bo Naylor and company still looks less settled from top to bottom.",
"Atlanta -162 is playable because the Braves can win this game in the first six or in the final three. Truist is inviting to pull power (about 335 to left, 325 to right), and even with a mild breeze in from right, 84° conditions still keep the ball lively. The Braves’ healthier run-producing core, including Austin Riley, gives them the better chance to cash in with men on base, while Miami’s lineup tends to need longer rallies to score in bunches. If Bryce Elder simply avoids the one crooked inning, Atlanta’s bullpen quality and home-field dimensions do the rest.",
"Yankees -177 lines up with a straightforward park-and-weather advantage. Yankee Stadium’s 314-foot right-field porch always matters, but tonight’s 81° temperature and wind out toward left also create opposite-field carry for right-handed hitters, so both sides of the power map are active. That favors New York’s lineup depth when Aaron Judge and Austin Wells are available and healthy enough to stack quality plate appearances. The Angels can absolutely hit a few mistakes, but over nine innings the Yankees’ stronger run-prevention floor and cleaner late-game options still justify favorite pricing.",
"Detroit -120 is a modest favorite with the cleaner path to a one- to three-run win. Comerica is big—around 345 to left and 420 to center—so extra-base production often comes from line drives in the gaps rather than cheap homers. In 73° weather with wind out to left, there’s a little added carry, but this remains a park that rewards defensive range and disciplined sequencing. That leans toward Detroit’s current form, especially with Colt Keith and Casey Mize available, while Kansas City’s attack around Bobby Witt Jr. is dangerous but more dependent on creating chaos than controlling pace.",
"Arizona at +123 is live because Camden’s current shape still asks hitters to earn left-field power, while rewarding disciplined contact to center-right. In warm 87.5° air with breeze out to center, line drives can keep running in this yard (about 333 down the left line, 400 center, 318 right). That supports the Diamondbacks’ patient, pressure style and gives Pfaadt more room for fly-ball mistakes than the old wall setup did. With Alek Thomas active and Baltimore still balancing availability around key contributors, this reads like a legitimate underdog shot rather than a lottery ticket.",
"Seattle -119 is built on environment first. Petco suppresses damage in many game states (roughly 334 left, 396 center, 322 right), and tonight’s cool 65° air with wind in from right further dampens pull-side carry. That setting raises the value of strike-throwing and outfield defense, both areas where Seattle’s current group has been steadier. With Andrés Muñoz available to close tight scripts and San Diego still piecing together consistency around a rotating active list, the Mariners have the cleaner nine-inning blueprint in a likely low-scoring game.",
"Tampa Bay -135 is less about headline talent and more about repeatable run creation. Rate Field can play fair-to-hitter in heat, but 14 mph in from right at 79° blunts some loft power and rewards teams that string quality at-bats (about 330 left, 400 center, 335 right). That profile fits Tampa Bay’s current offensive approach and bullpen matchup depth. With Cedric Mullins available and Chicago still in flux around several active-but-rotating pieces, the Rays project to manufacture scoring chances more consistently across innings, which is usually enough at this price.",
"Dodgers over Mets is still the side despite ugly-looking market pricing noise. Dodger Stadium’s dimensions are balanced (330-400-330) and tonight’s 62° marine-layer conditions usually mute cheap carry, but a slight wind out to right opens a narrow lane for left-handed lift. The difference is lineup pressure: Los Angeles can force stressful pitches in nearly every inning and then hand a lead to a deeper relief ladder. With key bats and late arms available on the Dodgers’ side, New York likely needs near-perfect sequencing to steal this one.",
"Philadelphia -141 makes sense in this weather band. Citizens Bank is compact to the corners (about 329 left, 330 right) and very punishable in warm 85° air with a push to center, so contact quality is likely to convert quickly into runs. That tends to favor the club with better middle-order thump and less bullpen leakage, which points Phillies. Aaron Nola’s availability gives the home side a higher-probability start profile, while the Cubs can absolutely ambush early but are more vulnerable if they fall behind and have to chase run prevention matchups.",
"Milwaukee -120 in a roof-controlled game is a trust-the-foundation play. American Family Field has power-friendly lines but a deep center pocket (roughly 344-400-345), and with the roof environment neutralized, randomness from wind disappears. That raises the importance of strike efficiency, defensive positioning, and bench leverage over nine innings. Milwaukee’s active group around Ashby and Uribe gives them more late-inning control points, while Toronto’s available pieces have flashed upside but less stability from inning to inning. In a neutral air game, the steadier structure is worth the favorite tag.",
"Minnesota +114 is a dog worth a long look because Target Field can punish impatient offenses. The park is roomy to center (around 404) with asymmetrical alleys, and in 67° air with only a light crosswind, this game should reward clean contact and situational execution over pure slugging. That setup narrows Boston’s power edge and boosts Minnesota’s path through defense, baserunning pressure, and timely extra-base hits. With their active core intact enough to run multiple scoring styles, the Twins have a realistic upset route rather than a thin one-inning miracle path.",
"Texas is the call even with noisy pricing because Sutter Health Park can turn ordinary fly balls into decision points. The corners are comparatively short with a deeper center field (roughly low-330s to the lines and just over 400 to center), and tonight’s modest breeze out to center in mild mid-60s weather favors gap power and aggressive baserunning. That profile supports the Rangers’ better lineup length and run-conversion quality over nine innings. With key veterans active and Oakland still carrying more uncertainty in both rotation depth and relief bridge, Texas owns more stable ways to win.",
"San Francisco -104 is a thin edge, but a real one. Great American is compact to both poles (about 328 left, 325 right) and generally boosts scoring variance, yet tonight’s 13 mph wind in from left tempers some of the easy pull-side carry. In that blend, the club that controls counts and keeps free runners off tends to separate late. The Giants’ current active group gives them a slightly cleaner prevention profile, while Cincinnati’s upside remains dangerous but more streak-dependent. In a near pick’em, that steadier late-game floor is enough to side Giants."
],
'2026-04-14-plus-money.html':[
"At +102, St. Louis is the kind of underdog that has real structural support. Busch usually stretches fly balls in the gaps, but 87° heat and a 14 mph wind toward left shorten the decision window for pitchers who miss arm-side. That matters against a Cardinals order built to do damage from the right side, and it gives McGreevy a bit more margin if he stays ahead in counts. With Burleson and Pallante active and the bullpen shape intact, the home dog has multiple viable paths: early pressure, then leverage innings.",
"Arizona at +123 isn’t a blind price grab; it fits the park and conditions. Camden’s renovated left side still suppresses some routine pull homers, but in hot 87.5° air with breeze to center, line-drive offense can snowball quickly. That favors a Diamondbacks group that can run, take extra bases, and force deep counts rather than waiting only on long balls. With Alek Thomas available and Baltimore still juggling pieces around key contributors, Arizona’s underdog route looks broad enough to play—especially if they seize tempo in the middle innings.",
"Minnesota +114 is attractive because this matchup projects tighter than the line suggests. Target Field’s deep center and uneven alleys reduce easy damage, and tonight’s cooler 67° setup with a mild crosswind should reward complete at-bats over all-or-nothing swings. That trims some of Boston’s top-end slug profile while keeping the game in the range where one sharp start and two clean bullpen turns can decide it. With the Twins’ active group healthy enough to defend and pressure on the bases, this dog has legitimate win equity, not just theoretical value."
],
'2026-04-14-run-totals.html':[
"OVER 9.36 is the lean because Yankee Stadium gives both lineups live home-run lanes: 314 down the right-field line, 318 to left, and weather at 81° with wind nudging toward left. With Aaron Judge active and the Angels carrying enough available bats to answer, this profiles as a game where one early crooked number forces both bullpens into stress innings.",
"OVER 9.59 fits PNC tonight. The park’s deep center (410) usually protects pitchers, but 79° air and a 13 mph push to left increase carry on pulled contact, and both clubs have active middle-order pieces who can punish mistakes. Once this game gets to middle relief, run acceleration is very plausible.",
"OVER 8.25 makes sense at Citizens Bank because the yard is tight to both corners (329/330) and the weather is offense-friendly: 85° with wind out to center. Both lineups have enough healthy power to cash in quickly, so this total can clear on standard game flow without needing extra innings.",
"OVER 8.5 at Busch is playable because hot 87° conditions plus a 14 mph breeze to left offset some of the park’s usual spaciousness. With several active run producers on each side, one starter wobble can turn this into a bullpen game by the sixth, which is often where overs get paid.",
"OVER 8.75 in Baltimore is driven by environment and lineup style. Camden’s dimensions still allow line drives to play in center-right, and at 87.5° with wind out to center, hard contact should carry. Arizona and Baltimore both have active speed-and-gap pieces that can stack doubles and pressure defensive execution.",
"OVER 8.88 in Atlanta stays live even with a light breeze in from right because 84° air keeps the ball moving at Truist. The park’s short corners and both teams’ available power bats create multiple three-run-inning paths, especially once starters hand off to middle relief.",
"OVER 7.88 at Comerica is a modest over, not a shootout call. The park is huge to center (420), but wind out to left at 13 mph helps pull-side loft, and both offenses have enough active table-setters to convert doubles into multi-run frames. This number can clear with ordinary sequencing.",
"OVER 8.55 in Houston is a roof-game over: controlled temperature, consistent batter’s eye, and dimensions that still reward true barrels. With both teams carrying active hitters who can punish first-pitch strikes, the path is steady run accumulation rather than weather-driven chaos.",
"UNDER 7.62 at Petco is built on suppression factors. Cool mid-60s air, wind in from right, and a park that already limits easy carry all point toward fewer extra-base clusters. With available late-inning arms on both sides, this projects as a game where runs must be manufactured.",
"OVER 8.0 in Los Angeles is a number small enough to clear even in cooler marine-layer air. Dodger Stadium’s balanced 330-400-330 layout plus a slight breeze out to right gives left-handed lift a lane, and both lineups have active bats capable of flipping the board in one inning.",
"OVER 7.88 in Minnesota is a measured over tied to game shape more than weather. Target Field is roomy, but both clubs have active hitters who run counts and force bullpen exposure. At this total, two quality starts can still lose the under if middle innings get traffic-heavy.",
"OVER 8.75 in Cincinnati asks you to respect the park first. Great American’s short lines (328/325) keep home-run probability elevated even when wind is in from left, and warm 80° air preserves carry enough for mistakes to leave. With both offenses healthy enough to trade punches, nine runs is reachable.",
"OVER 9.5 in Texas-A’s is aggressive but justified by the Sacramento run environment. Sutter Health Park’s shorter corners and deeper center encourage both power and extra-base chaos, and a gentle breeze to center supports carry. With active veteran bats on both rosters, this can become a high-contact, high-traffic game quickly.",
"OVER 8.33 at Rate Field survives the wind-in note because this park still rewards hard pull contact and both sides bring active bats that can string together damage without waiting on solo homers. In 79° conditions, doubles and bullpen walks can do most of the work.",
"UNDER 7.0 in Milwaukee is a classic roof-context under. No wind noise, deep center-field pocket, and two staffs with enough active leverage arms to protect narrow leads push this toward a controlled scoring game. At a low number, the under still has room if early traffic gets stranded."
]
}

for fn, arr in repls.items():
    p = base / fn
    t = p.read_text()
    matches = list(re.finditer(r'<p class="lede">.*?</p>', t, flags=re.S))
    if len(matches) != len(arr):
        raise SystemExit(f'{fn}: expected {len(matches)} ledes, got replacements {len(arr)}')
    out = []
    last = 0
    for m, new in zip(matches, arr):
        out.append(t[last:m.start()])
        out.append(f'<p class="lede">{new}</p>')
        last = m.end()
    out.append(t[last:])
    p.write_text(''.join(out))
    print('updated', fn)
