from pathlib import Path
import re

base=Path('/Users/asmith/.openclaw/workspace/sportzballz.io')
updates={
'2026-04-14.html':[
"Pittsburgh feels like the home side that fits its own park: PNC’s broad alleys (383 left-center, 410 to center) reward pitchers who keep the ball on the ground and outfielders who can close distance, and that script favors Mitch Keller over nine innings. With Bryan Reynolds and Brandon Lowe both active, the Pirates also have enough left-handed traffic to keep Washington from matching up cleanly late. Warm evening air with a crosswind can turn routine flies into long outs here, which usually helps the club that prevents the extra ninety feet.",
"At Truist, where the lines are inviting but the right-center gap still asks real questions, Atlanta’s lineup depth is the cleaner answer. Austin Riley active in the middle and Chris Sale available on the run-prevention side gives the Braves two ways to control the game if Max Meyer navigates early trouble. Miami has active bodies, but this is the kind of mild-weather game where bullpen handoffs matter more than one loud swing, and Atlanta’s chain is sturdier.",
"Comerica can make hitters feel the outfield is moving away from them, and that geometry (420 in dead center) supports Detroit’s profile tonight. Framber Valdez’s contact shape plus an active Tigers core featuring Colt Keith and Casey Mize points to fewer free bases and fewer damaging mistakes. Kansas City still carries star punch with Bobby Witt Jr. active, but in a cooler Midwest setup this leans toward the side that can defend long innings without cracking.",
"Arizona at this number is playable because Camden now asks for full innings, not just short-porch aggression; the deep left-center lane and 410 to center tend to reward teams that run clean routes and take the extra base. Merrill Kelly’s strike-throwing rhythm matches that environment, while Corbin Carroll and Gabriel Moreno active gives the Diamondbacks speed plus contact pressure. Baltimore can score in bursts, but this weather-and-park combination narrows the gap and makes the underdog’s complete game path real.",
"Busch Stadium usually turns this matchup into a conversation about discipline, and St. Louis is equipped for that argument tonight. With Iván Herrera and Alec Burleson active, the Cardinals can string together quality plate appearances in a park that punishes lazy fly-ball plans. Cleveland’s lineup is competitive, yet in warm but manageable air and a spacious center-field backdrop, the edge goes to the club with the more stable bridge from starter to late leverage.",
"Tampa Bay is the practical side at Rate Field because this park rewards teams that convert chances rather than wait on one miracle inning. Shane McClanahan’s miss-bat profile travels, and active support from Drew Rasmussen plus Chandler Simpson gives the Rays both prevention and speed pressure. Chicago’s younger active group can flash, but with damp air and a chance of interruption, cleaner defensive innings usually decide this type of game.",
"Petco after sundown still plays like a place where one extra mistake is the whole story, and Seattle is built for that kind of script. Bryan Woo active with Cal Raleigh behind the plate gives the Mariners a command-and-receiving pairing suited to deep alleys and marine air. San Diego has headline bats active, including Tatis, but if this stays in the lane of sequencing and bullpen execution, Seattle’s run-prevention texture holds up better.",
"Yankee Stadium makes every fly ball feel like an argument, and New York brings the louder side of that debate with Aaron Judge and Cody Bellinger both active. The short porches can hide a lot of imperfect contact, and the Yankees’ top-third power gives them more routes to a crooked inning than the Angels usually produce in this setting. With warm conditions and manageable wind, backing the favorite is less about romance and more about repeatable damage.",
"The Dodgers at home remain the steadier ticket because Dodger Stadium’s big gaps and cooler night air reward complete rosters, not quick surges. Yamamoto’s strike efficiency paired with active late options like Vesia and Treinen means Los Angeles can keep run prevention intact from first pitch to final out. The Mets can create pressure, but in this ballpark that pressure has to be sustained, and the Dodgers are better built to absorb it.",
"Milwaukee gets the nod in a roof-flexible environment where outside weather can be muted and execution sits in plain view. With Brice Turang active at the table-setting end and Brandon Woodruff active on the mound side, the Brewers carry a balanced profile in a neutral-dimension park. Toronto has active talent, but this matchup projects as a possession game, and Milwaukee commits fewer defensive and bullpen leaks over nine innings.",
"Minnesota at plus money is worth it because Target Field’s big center alley and cooler spring conditions reduce cheap slug advantages and put a premium on athletic run prevention. Byron Buxton and Brooks Lee active gives the Twins range and baserunning pressure in exactly the spots that decide tight games. Boston has dangerous bats, but this looks like a game where sequencing and outfield coverage matter more than brand-name thunder.",
"In Cincinnati’s compact yard, the instinct is always to chase chaos, but the better read here is San Francisco’s ability to miss bats before the fences matter. Robbie Ray’s strikeout lane and active support from Harrison Bader and Casey Schmitt gives the Giants a cleaner path through volatile innings. Warm air can juice the ball, sure, yet the club that steals more strike one counts in this park usually controls the final shape of scoring.",
"Texas is the side in Sacramento because Sutter Health Park can flip quickly when one lineup is deeper through spots five to seven, and the Rangers bring that depth with Corey Seager and Evan Carter active. The open-air setting and modest breeze allow runs, but they also punish shallow bullpens once traffic starts. Texas has more ways to score without the home run and more trusted outs at the end, which is a strong favorite profile.",
"Philadelphia fits Citizens Bank’s personality: short lines, quick momentum shifts, and heavy leverage innings where command has to survive noise. Bryce Harper and Aaron Nola active gives the Phillies both the impact bat and the stabilizing arm you want in this park. Chicago can absolutely trade punches, but with warm air and a live carry window, the better late-game bullpen architecture is why the Phillies remain the right side."
],
'2026-04-14-plus-money.html':[
"The underdog case for Arizona starts with fit: Camden’s deeper left-center geometry rewards teams that defend space and run the bases with intent, and the Diamondbacks do both when Corbin Carroll and Gabriel Moreno are active. Merrill Kelly’s tempo also matters in this park because free passes turn into two-base damage quickly. Baltimore’s lineup is dangerous, but this price gives room for Arizona’s cleaner run-prevention script.",
"St. Louis as a short dog is a logical buy in Busch, where long alleys and a 400-foot center force offenses to earn every run. With Iván Herrera and Alec Burleson active, the Cardinals have enough middle-order stability to win inning by inning instead of waiting for one blast. Cleveland can win on contact quality, yet the bullpen texture and park context make this a fair underdog investment.",
"Minnesota at plus money is the kind of April edge that comes from environment as much as talent. Target Field’s broad dimensions and cool air reduce easy carry, and active pieces like Buxton and Brooks Lee tilt the game toward range, pressure, and first-to-third baseball. Boston’s active group can score, but this number underrates the Twins’ defensive floor and late-inning run prevention."
],
'2026-04-14-run-totals.html':[
"The over is still live in Pittsburgh because PNC’s big alleys create run-building doubles even when the ball does not leave the yard, and both lineups bring active table-setters who can turn singles into pressure. Reynolds and Lowe being available for the Pirates, with Abrams active for Washington, points to traffic in multiple innings. Warm conditions with steady breeze favor continuous action over a quiet, three-true-outcomes game.",
"Atlanta-Miami profiles over the number because Truist’s short lines reward pull contact, and both clubs have active middle-order bats capable of quick two-run turns. Riley’s presence for Atlanta raises the extra-base ceiling, while Miami’s active depth keeps scoring alive against second and third pitching looks. In warm, dry air, this total can be threatened by the sixth inning.",
"The under in Detroit-Kansas City is the sharper lane because Comerica’s deep center and long gaps mute cheap power and stretch innings toward stranded runners. With front-line starters and active defensive anchors on both sides, run creation should require sustained execution rather than one mistake. Even with Witt active, this park-weather mix supports a lower-scoring script.",
"St. Louis-Cleveland leans over because Busch does not kill offense when both teams can string line drives and force pitchers to work from the stretch. Active bats like Herrera for St. Louis and the Guardians’ catching core keep plate appearances competitive deep into counts. With warm air and manageable wind, this total is reachable through accumulation instead of pure homer variance.",
"Rays-White Sox under fits the board: two staffs with swing-and-miss ability, cooler damp conditions, and a total that asks for near-constant conversion. Tampa’s active run prevention group and Chicago’s youth-heavy lineup profile point to uneven scoring pockets rather than sustained rallies. If early command holds, this has a strong 4-2 type shape.",
"Seattle-San Diego under is built on park reality more than optimism. Petco’s night air and deep alleys suppress carry, and both probable starters are comfortable pitching ahead in counts. With Raleigh active for Seattle and quality defenders available on both sides, basepaths should stay relatively clean, making seven runs a high bar.",
"Yankees-Angels over remains appealing because this park can convert routine fly balls into immediate damage, especially with Judge and Bellinger active in New York’s power lane. The Angels have enough active bats to contribute their share once bullpens cycle through middle relief. In warm Bronx weather, this number is vulnerable to one big inning plus late add-ons.",
"Dodgers-Mets over is modest enough to play because both orders have active impact hitters and the total does not demand a shootout. Even in cooler Chavez Ravine air, doubles in the gaps and bullpen matchups can pile up to eight. If either starter leaves by the sixth, the over has multiple paths home.",
"Twins-Red Sox over at this number is less about park inflation and more about lineup depth meeting a reachable target. Buxton active for Minnesota and Boston’s active athletic core can create runs without waiting for three-run homers. Target Field’s size can suppress one swing, but not necessarily overall baserunner volume.",
"Giants-Reds over is the classic Great American setup: short corners, lively carry, and one misplaced fastball changing the whole inning. With Elly active for Cincinnati and multiple active contact bats for San Francisco, the game can snowball quickly once traffic starts. A total in this range is high, but the park earns that respect.",
"Phillies-Cubs over fits Citizens Bank’s run environment, where compact alleys and aggressive swings can manufacture offense in bunches. Harper and Bohm active for Philadelphia plus active top-half bats for Chicago point to pressure on both starters before the late innings. With warm air and a friendly carry profile, ten runs is not a stretch outcome.",
"Diamondbacks-Orioles under is a fair contrarian look because Camden’s deeper left field now asks hitters to complete at-bats rather than clip easy homers. Kelly’s efficiency and Baltimore’s capable run-prevention pieces can keep this game in controlled tempo early. With evening air cooling and fewer cheap mistakes expected, nine runs is a meaningful ask.",
"Brewers-Blue Jays under makes sense in a roof-capable game where wind variables are minimized and strike-throwing can dominate. Woodruff active for Milwaukee and Toronto’s active defensive pieces point toward shorter rallies and more clean innings. At seven, every shutdown frame matters, and this matchup has enough of them.",
"Rangers-Athletics under is playable even in a park that can run hot because both sides carry active bullpen depth capable of closing the late windows. Texas can score in waves, but Oakland has enough arms to prevent a full breakaway script. In mild Sacramento night conditions, the median outcome sits just under this number."
]
}

for fname, ledes in updates.items():
    path=base/fname
    text=path.read_text()
    matches=list(re.finditer(r'<p class="lede">.*?</p>', text, flags=re.S))
    if len(matches)!=len(ledes):
        raise SystemExit(f'{fname}: expected {len(ledes)} ledes but found {len(matches)}')
    parts=[]
    last=0
    for m,new in zip(matches, ledes):
        parts.append(text[last:m.start()])
        parts.append(f'<p class="lede">{new}</p>')
        last=m.end()
    parts.append(text[last:])
    path.write_text(''.join(parts))
    print(f'updated {fname} ({len(ledes)} ledes)')
